DELETE FROM TBLSUPPORTSYSTEM
WHERE STUDENT_SEQ = 'S0496' AND open_course_seq = 'OL015'; --지원제도삭제
INSERT INTO TBLSUPPORTSYSTEM (STUDENT_SEQ, OPEN_COURSE_SEQ, TRAINING_INSENTIVE, EMPLOYEE_SUPPORT) 
VALUES ('S0496', 'OL015', 'Y', 'Y'); --지원제도 입력
UPDATE TBLSUPPORTSYSTEM SET EMPLOYEE_SUPPORT = 'N'
WHERE STUDENT_SEQ = 'S0496' AND open_course_seq = 'OL015'; --지원여부수정

select DISTINCT
STUDENT_SEQ as "내일배움 지원교육생번호"
from TBLSUPPORTSYSTEM 
where TRAINING_INSENTIVE = 'Y'; --내일배움 훈련장려금 수령교육생 조회

select DISTINCT
STUDENT_SEQ as "국민취업지원제도 지원교육생번호"
 from TBLSUPPORTSYSTEM
where EMPLOYEE_SUPPORT = 'Y'; --국민취업 지원제도 국민취업제도 수령 교육생조회