SET DEFINE OFF

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0381', 'OL001', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0411', 'OL001', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0133', 'OL001', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0286', 'OL001', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0358', 'OL001', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0315', 'OL001', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0308', 'OL001', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0417', 'OL001', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0307', 'OL001', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0249', 'OL001', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0138', 'OL001', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0183', 'OL001', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0416', 'OL001', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0106', 'OL001', 'N', NULL, to_date('2021-09-10'), NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0300', 'OL001', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0468', 'OL001', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0038', 'OL001', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0013', 'OL001', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0171', 'OL001', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0473', 'OL001', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0004', 'OL001', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0035', 'OL001', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0276', 'OL001', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0294', 'OL001', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0160', 'OL001', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0152', 'OL001', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0007', 'OL001', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0066', 'OL001', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0497', 'OL001', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0392', 'OL001', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0230', 'OL002', 'N', NULL, to_date('2021-09-15'), NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0022', 'OL002', 'N', NULL, to_date('2021-09-10'), NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0409', 'OL002', 'N', NULL, to_date('2021-09-22'), NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0218', 'OL002', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0397', 'OL002', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0177', 'OL002', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0303', 'OL002', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0141', 'OL002', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0426', 'OL002', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0410', 'OL002', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0479', 'OL002', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0284', 'OL002', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0258', 'OL002', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0305', 'OL002', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0487', 'OL002', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0465', 'OL002', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0071', 'OL002', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0467', 'OL002', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0084', 'OL002', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0168', 'OL002', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0231', 'OL002', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0002', 'OL002', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0309', 'OL002', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0268', 'OL002', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0328', 'OL002', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0014', 'OL002', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0033', 'OL002', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0275', 'OL002', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0481', 'OL002', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0086', 'OL002', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0373', 'OL003', 'N', NULL, to_date('2021-09-13'), NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0115', 'OL003', 'N', NULL, to_date('2021-08-15'), NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0450', 'OL003', 'N', NULL, to_date('2021-08-18'), NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0389', 'OL003', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0137', 'OL003', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0429', 'OL003', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0001', 'OL003', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0451', 'OL003', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0344', 'OL003', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0132', 'OL003', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0082', 'OL003', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0407', 'OL003', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0352', 'OL003', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0471', 'OL003', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0018', 'OL003', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0270', 'OL003', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0441', 'OL003', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0125', 'OL003', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0158', 'OL003', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0079', 'OL003', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0126', 'OL003', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0304', 'OL003', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0107', 'OL003', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0292', 'OL003', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0310', 'OL003', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0472', 'OL003', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0099', 'OL003', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0104', 'OL003', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0419', 'OL003', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0431', 'OL003', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0163', 'OL004', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0030', 'OL004', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0385', 'OL004', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0096', 'OL004', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0463', 'OL004', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0390', 'OL004', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0209', 'OL004', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0029', 'OL004', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0069', 'OL004', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0448', 'OL004', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0170', 'OL004', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0380', 'OL004', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0148', 'OL004', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0179', 'OL004', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0227', 'OL004', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0361', 'OL004', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0193', 'OL004', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0025', 'OL004', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0399', 'OL004', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0427', 'OL004', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0306', 'OL004', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0077', 'OL004', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0271', 'OL004', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0256', 'OL004', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0197', 'OL004', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0374', 'OL004', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0333', 'OL005', 'N', NULL, to_date('2021-10-01'), NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0330', 'OL005', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0348', 'OL005', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0093', 'OL005', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0289', 'OL005', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0295', 'OL005', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0100', 'OL005', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0111', 'OL005', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0220', 'OL005', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0298', 'OL005', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0080', 'OL005', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0254', 'OL005', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0456', 'OL005', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0280', 'OL005', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0009', 'OL005', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0151', 'OL005', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0322', 'OL005', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0321', 'OL005', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0482', 'OL005', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0150', 'OL005', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0387', 'OL005', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0169', 'OL005', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0012', 'OL005', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0302', 'OL005', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0087', 'OL005', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0175', 'OL005', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0110', 'OL006', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0207', 'OL006', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0440', 'OL006', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0136', 'OL006', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0173', 'OL006', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0312', 'OL006', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0241', 'OL006', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0041', 'OL006', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0147', 'OL006', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0283', 'OL006', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0401', 'OL006', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0078', 'OL006', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0439', 'OL006', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0461', 'OL006', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0043', 'OL006', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0432', 'OL006', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0117', 'OL006', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0118', 'OL006', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0316', 'OL006', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0055', 'OL006', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0496', 'OL006', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0194', 'OL006', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0403', 'OL006', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0108', 'OL006', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0262', 'OL006', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0089', 'OL006', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0486', 'OL007', 'N', NULL, to_date('2021-01-15'), NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0042', 'OL007', 'Y', to_date('2021-06-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0250', 'OL007', 'Y', to_date('2021-06-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0057', 'OL007', 'Y', to_date('2021-06-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0083', 'OL007', 'Y', to_date('2021-06-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0415', 'OL007', 'Y', to_date('2021-06-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0488', 'OL007', 'Y', to_date('2021-06-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0076', 'OL007', 'Y', to_date('2021-06-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0222', 'OL007', 'Y', to_date('2021-06-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0213', 'OL007', 'Y', to_date('2021-06-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0116', 'OL007', 'Y', to_date('2021-06-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0366', 'OL007', 'Y', to_date('2021-06-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0225', 'OL007', 'Y', to_date('2021-06-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0145', 'OL007', 'Y', to_date('2021-06-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0003', 'OL007', 'Y', to_date('2021-06-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0273', 'OL007', 'Y', to_date('2021-06-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0109', 'OL007', 'Y', to_date('2021-06-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0212', 'OL007', 'Y', to_date('2021-06-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0293', 'OL007', 'Y', to_date('2021-06-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0354', 'OL007', 'Y', to_date('2021-06-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0092', 'OL007', 'Y', to_date('2021-06-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0336', 'OL007', 'Y', to_date('2021-06-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0059', 'OL007', 'Y', to_date('2021-06-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0164', 'OL007', 'Y', to_date('2021-06-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0332', 'OL007', 'Y', to_date('2021-06-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0350', 'OL007', 'Y', to_date('2021-06-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0049', 'OL007', 'Y', to_date('2021-06-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0236', 'OL007', 'Y', to_date('2021-06-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0425', 'OL007', 'Y', to_date('2021-06-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0474', 'OL008', 'Y', to_date('2021-05-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0097', 'OL008', 'Y', to_date('2021-05-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0045', 'OL008', 'Y', to_date('2021-05-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0395', 'OL008', 'Y', to_date('2021-05-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0378', 'OL008', 'Y', to_date('2021-05-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0068', 'OL008', 'Y', to_date('2021-05-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0422', 'OL008', 'Y', to_date('2021-05-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0060', 'OL008', 'Y', to_date('2021-05-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0323', 'OL008', 'Y', to_date('2021-05-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0121', 'OL008', 'Y', to_date('2021-05-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0075', 'OL008', 'Y', to_date('2021-05-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0036', 'OL008', 'Y', to_date('2021-05-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0383', 'OL008', 'Y', to_date('2021-05-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0363', 'OL008', 'Y', to_date('2021-05-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0347', 'OL008', 'Y', to_date('2021-05-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0235', 'OL008', 'Y', to_date('2021-05-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0480', 'OL008', 'Y', to_date('2021-05-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0005', 'OL008', 'Y', to_date('2021-05-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0253', 'OL008', 'Y', to_date('2021-05-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0088', 'OL008', 'Y', to_date('2021-05-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0238', 'OL008', 'Y', to_date('2021-05-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0134', 'OL008', 'Y', to_date('2021-05-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0282', 'OL008', 'Y', to_date('2021-05-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0423', 'OL008', 'Y', to_date('2021-05-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0046', 'OL008', 'Y', to_date('2021-05-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0037', 'OL008', 'Y', to_date('2021-05-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0301', 'OL008', 'Y', to_date('2021-05-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0337', 'OL008', 'Y', to_date('2021-05-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0459', 'OL008', 'Y', to_date('2021-05-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0198', 'OL008', 'Y', to_date('2021-05-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0226', 'OL009', 'Y', to_date('2021-08-09'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0433', 'OL009', 'Y', to_date('2021-08-09'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0445', 'OL009', 'Y', to_date('2021-08-09'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0044', 'OL009', 'Y', to_date('2021-08-09'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0149', 'OL009', 'Y', to_date('2021-08-09'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0154', 'OL009', 'Y', to_date('2021-08-09'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0182', 'OL009', 'Y', to_date('2021-08-09'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0128', 'OL009', 'Y', to_date('2021-08-09'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0364', 'OL009', 'Y', to_date('2021-08-09'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0393', 'OL009', 'Y', to_date('2021-08-09'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0103', 'OL009', 'Y', to_date('2021-08-09'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0357', 'OL009', 'Y', to_date('2021-08-09'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0032', 'OL009', 'Y', to_date('2021-08-09'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0498', 'OL009', 'Y', to_date('2021-08-09'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0215', 'OL009', 'Y', to_date('2021-08-09'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0161', 'OL009', 'Y', to_date('2021-08-09'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0196', 'OL009', 'Y', to_date('2021-08-09'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0381', 'OL009', 'Y', to_date('2021-08-09'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0411', 'OL009', 'Y', to_date('2021-08-09'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0133', 'OL009', 'Y', to_date('2021-08-09'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0286', 'OL009', 'Y', to_date('2021-08-09'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0358', 'OL009', 'Y', to_date('2021-08-09'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0315', 'OL009', 'Y', to_date('2021-08-09'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0308', 'OL009', 'Y', to_date('2021-08-09'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0417', 'OL009', 'Y', to_date('2021-08-09'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0307', 'OL009', 'Y', to_date('2021-08-09'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0249', 'OL009', 'Y', to_date('2021-08-09'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0138', 'OL009', 'Y', to_date('2021-08-09'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0183', 'OL009', 'Y', to_date('2021-08-09'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0416', 'OL009', 'Y', to_date('2021-08-09'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0106', 'OL010', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0300', 'OL010', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0468', 'OL010', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0038', 'OL010', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0013', 'OL010', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0171', 'OL010', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0473', 'OL010', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0004', 'OL010', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0035', 'OL010', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0276', 'OL010', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0294', 'OL010', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0160', 'OL010', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0152', 'OL010', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0007', 'OL010', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0066', 'OL010', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0497', 'OL010', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0392', 'OL010', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0230', 'OL010', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0022', 'OL010', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0409', 'OL010', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0218', 'OL010', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0397', 'OL010', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0177', 'OL010', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0303', 'OL010', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0141', 'OL010', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0426', 'OL010', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0410', 'OL011', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0479', 'OL011', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0284', 'OL011', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0258', 'OL011', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0305', 'OL011', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0487', 'OL011', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0465', 'OL011', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0071', 'OL011', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0467', 'OL011', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0084', 'OL011', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0168', 'OL011', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0231', 'OL011', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0002', 'OL011', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0309', 'OL011', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0268', 'OL011', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0328', 'OL011', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0014', 'OL011', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0033', 'OL011', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0275', 'OL011', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0481', 'OL011', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0086', 'OL011', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0373', 'OL011', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0115', 'OL011', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0450', 'OL011', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0389', 'OL011', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0137', 'OL011', 'Y', to_date('2021-08-28'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0429', 'OL012', 'Y', to_date('2021-04-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0001', 'OL012', 'Y', to_date('2021-04-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0451', 'OL012', 'Y', to_date('2021-04-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0344', 'OL012', 'Y', to_date('2021-04-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0132', 'OL012', 'Y', to_date('2021-04-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0082', 'OL012', 'Y', to_date('2021-04-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0407', 'OL012', 'Y', to_date('2021-04-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0352', 'OL012', 'Y', to_date('2021-04-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0471', 'OL012', 'Y', to_date('2021-04-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0018', 'OL012', 'Y', to_date('2021-04-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0270', 'OL012', 'Y', to_date('2021-04-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0441', 'OL012', 'Y', to_date('2021-04-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0125', 'OL012', 'Y', to_date('2021-04-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0158', 'OL012', 'Y', to_date('2021-04-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0079', 'OL012', 'Y', to_date('2021-04-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0126', 'OL012', 'Y', to_date('2021-04-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0304', 'OL012', 'Y', to_date('2021-04-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0107', 'OL012', 'Y', to_date('2021-04-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0292', 'OL012', 'Y', to_date('2021-04-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0310', 'OL012', 'Y', to_date('2021-04-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0472', 'OL012', 'Y', to_date('2021-04-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0099', 'OL012', 'Y', to_date('2021-04-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0104', 'OL012', 'Y', to_date('2021-04-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0419', 'OL012', 'Y', to_date('2021-04-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0431', 'OL012', 'Y', to_date('2021-04-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0163', 'OL012', 'Y', to_date('2021-04-30'), NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0030', 'OL013', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0385', 'OL013', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0096', 'OL013', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0463', 'OL013', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0390', 'OL013', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0209', 'OL013', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0029', 'OL013', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0069', 'OL013', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0448', 'OL013', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0170', 'OL013', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0380', 'OL013', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0148', 'OL013', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0179', 'OL013', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0227', 'OL013', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0361', 'OL013', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0193', 'OL013', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0025', 'OL013', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0399', 'OL013', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0427', 'OL013', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0306', 'OL013', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0077', 'OL013', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0271', 'OL013', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0256', 'OL013', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0197', 'OL013', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0374', 'OL013', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0333', 'OL013', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0330', 'OL013', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0348', 'OL013', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0093', 'OL013', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0289', 'OL013', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0295', 'OL014', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0100', 'OL014', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0111', 'OL014', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0220', 'OL014', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0298', 'OL014', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0080', 'OL014', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0254', 'OL014', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0456', 'OL014', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0280', 'OL014', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0009', 'OL014', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0151', 'OL014', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0322', 'OL014', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0321', 'OL014', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0482', 'OL014', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0150', 'OL014', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0387', 'OL014', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0169', 'OL014', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0012', 'OL014', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0302', 'OL014', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0087', 'OL014', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0175', 'OL014', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0110', 'OL014', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0207', 'OL014', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0440', 'OL014', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0136', 'OL014', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0173', 'OL014', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0312', 'OL014', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0241', 'OL014', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0041', 'OL014', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0147', 'OL014', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0283', 'OL015', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0401', 'OL015', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0078', 'OL015', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0439', 'OL015', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0461', 'OL015', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0043', 'OL015', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0432', 'OL015', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0117', 'OL015', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0118', 'OL015', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0316', 'OL015', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0055', 'OL015', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0496', 'OL015', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0194', 'OL015', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0403', 'OL015', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0108', 'OL015', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0262', 'OL015', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0089', 'OL015', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0486', 'OL015', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0042', 'OL015', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0250', 'OL015', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0057', 'OL015', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0083', 'OL015', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0415', 'OL015', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0488', 'OL015', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0076', 'OL015', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0222', 'OL015', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0213', 'OL015', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0116', 'OL015', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0366', 'OL015', NULL, NULL, NULL, NULL);

INSERT INTO TBLREGISTER (STUDENT_SEQ, OPEN_COURSE_SEQ, COMPLETION_STATUS, COMPLETION_DATE, DROPOUT_DATE, EVALUTION_SCORE) 
VALUES ('S0225', 'OL015', NULL, NULL, NULL, NULL);

