SET DEFINE OFF

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS001', 'SUB001', 'T001', 'B002', to_date('2021-09-08', 'YYYY-MM-DD'), to_date('2021-10-08', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 20, 40, 40, 'OL001');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS002', 'SUB006', 'T001', 'B016', to_date('2021-10-09', 'YYYY-MM-DD'), to_date('2021-11-08', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 30, 30, 40, 'OL001');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS003', 'SUB007', 'T001', 'B020', to_date('2021-11-09', 'YYYY-MM-DD'), to_date('2021-12-09', 'YYYY-MM-DD'), '강의중', 'N', 'N', 20, 40, 50, 'OL001');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS004', 'SUB010', 'T001', 'B030', to_date('2021-12-10', 'YYYY-MM-DD'), to_date('2022-01-09', 'YYYY-MM-DD'), '강의예정', 'N', 'N', 20, 40, 40, 'OL001');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS005', 'SUB021', 'T001', 'B061', to_date('2022-01-10', 'YYYY-MM-DD'), to_date('2022-03-07', 'YYYY-MM-DD'), '강의예정', 'N', 'N', 20, 30, 50, 'OL001');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS006', 'SUB040', 'T008', 'B119', to_date('2021-08-01', 'YYYY-MM-DD'), to_date('2021-08-31', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 20, 40, 40, 'OL002');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS007', 'SUB033', 'T008', 'B098', to_date('2021-09-01', 'YYYY-MM-DD'), to_date('2021-10-01', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 20, 30, 50, 'OL002');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS008', 'SUB021', 'T008', 'B061', to_date('2021-10-02', 'YYYY-MM-DD'), to_date('2021-11-01', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 20, 30, 50, 'OL002');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS009', 'SUB037', 'T008', 'B109', to_date('2021-11-02', 'YYYY-MM-DD'), to_date('2021-12-02', 'YYYY-MM-DD'), '강의중', 'N', 'N', 20, 30, 50, 'OL002');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS010', 'SUB031', 'T008', 'B092', to_date('2021-12-03', 'YYYY-MM-DD'), to_date('2022-01-28', 'YYYY-MM-DD'), '강의예정', 'N', 'N', 40, 30, 30, 'OL002');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS011', 'SUB001', 'T003', 'B002', to_date('2021-08-13', 'YYYY-MM-DD'), to_date('2021-09-12', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 20, 40, 40, 'OL003');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS012', 'SUB021', 'T003', 'B061', to_date('2021-09-13', 'YYYY-MM-DD'), to_date('2021-10-13', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 20, 30, 50, 'OL003');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS013', 'SUB022', 'T003', 'B066', to_date('2021-10-14', 'YYYY-MM-DD'), to_date('2021-11-13', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 30, 30, 50, 'OL003');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS014', 'SUB038', 'T003', 'B113', to_date('2021-11-14', 'YYYY-MM-DD'), to_date('2021-12-14', 'YYYY-MM-DD'), '강의중', 'N', 'N', 20, 30, 50, 'OL003');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS015', 'SUB039', 'T003', 'B117', to_date('2021-12-15', 'YYYY-MM-DD'), to_date('2022-02-09', 'YYYY-MM-DD'), '강의예정', 'N', 'N', 20, 30, 30, 'OL003');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS016', 'SUB001', 'T002', 'B003', to_date('2021-09-01', 'YYYY-MM-DD'), to_date('2021-10-01', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 20, 30, 50, 'OL004');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS017', 'SUB002', 'T002', 'B004', to_date('2021-10-02', 'YYYY-MM-DD'), to_date('2021-11-01', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 20, 50, 30, 'OL004');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS018', 'SUB014', 'T002', 'B040', to_date('2021-11-02', 'YYYY-MM-DD'), to_date('2021-12-02', 'YYYY-MM-DD'), '강의중', 'N', 'N', 20, 50, 30, 'OL004');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS019', 'SUB015', 'T002', 'B045', to_date('2021-12-03', 'YYYY-MM-DD'), to_date('2022-01-02', 'YYYY-MM-DD'), '강의예정', 'N', 'N', 20, 50, 30, 'OL004');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS020', 'SUB016', 'T002', 'B047', to_date('2022-01-03', 'YYYY-MM-DD'), to_date('2022-02-28', 'YYYY-MM-DD'), '강의예정', 'N', 'N', 20, 30, 30, 'OL004');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS021', 'SUB001', 'T005', 'B002', to_date('2021-09-02', 'YYYY-MM-DD'), to_date('2021-10-02', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 40, 30, 30, 'OL005');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS022', 'SUB009', 'T005', 'B027', to_date('2021-10-03', 'YYYY-MM-DD'), to_date('2021-11-02', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 20, 40, 40, 'OL005');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS023', 'SUB020', 'T005', 'B059', to_date('2021-11-03', 'YYYY-MM-DD'), to_date('2021-12-03', 'YYYY-MM-DD'), '강의중', 'N', 'N', 30, 30, 40, 'OL005');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS024', 'SUB027', 'T005', 'B079', to_date('2021-12-04', 'YYYY-MM-DD'), to_date('2022-01-03', 'YYYY-MM-DD'), '강의예정', 'N', 'N', 20, 40, 40, 'OL005');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS025', 'SUB036', 'T005', 'B107', to_date('2022-01-04', 'YYYY-MM-DD'), to_date('2022-03-01', 'YYYY-MM-DD'), '강의예정', 'N', 'N', 20, 40, 40, 'OL005');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS026', 'SUB008', 'T004', 'B024', to_date('2021-09-03', 'YYYY-MM-DD'), to_date('2021-10-04', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 20, 40, 40, 'OL006');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS027', 'SUB009', 'T004', 'B026', to_date('2021-10-05', 'YYYY-MM-DD'), to_date('2021-11-05', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 30, 30, 40, 'OL006');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS028', 'SUB020', 'T004', 'B058', to_date('2021-11-05', 'YYYY-MM-DD'), to_date('2021-12-20', 'YYYY-MM-DD'), '강의중', 'N', 'N', 20, 50, 30, 'OL006');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS029', 'SUB033', 'T004', 'B098', to_date('2021-12-20', 'YYYY-MM-DD'), to_date('2021-01-20', 'YYYY-MM-DD'), '강의예정', 'N', 'N', 20, 20, 60, 'OL006');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS030', 'SUB013', 'T004', 'B039', to_date('2021-01-20', 'YYYY-MM-DD'), to_date('2022-04-03', 'YYYY-MM-DD'), '강의예정', 'N', 'N', 40, 40, 20, 'OL006');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS031', 'SUB001', 'T002', 'B001', to_date('2021-01-01', 'YYYY-MM-DD'), to_date('2021-01-31', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 20, 40, 40, 'OL007');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS032', 'SUB002', 'T002', 'B006', to_date('2021-02-01', 'YYYY-MM-DD'), to_date('2021-03-03', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 30, 30, 40, 'OL007');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS033', 'SUB014', 'T002', 'B041', to_date('2021-03-04', 'YYYY-MM-DD'), to_date('2021-04-03', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 20, 50, 30, 'OL007');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS034', 'SUB015', 'T002', 'B043', to_date('2021-04-04', 'YYYY-MM-DD'), to_date('2021-05-04', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 20, 20, 60, 'OL007');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS035', 'SUB016', 'T002', 'B046', to_date('2021-05-05', 'YYYY-MM-DD'), to_date('2021-06-30', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 40, 40, 20, 'OL007');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS036', 'SUB008', 'T008', 'B023', to_date('2020-12-01', 'YYYY-MM-DD'), to_date('2020-12-31', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 20, 40, 40, 'OL008');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS037', 'SUB009', 'T008', 'B027', to_date('2021-01-01', 'YYYY-MM-DD'), to_date('2021-01-31', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 30, 30, 40, 'OL008');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS038', 'SUB036', 'T008', 'B107', to_date('2021-02-01', 'YYYY-MM-DD'), to_date('2021-03-03', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 20, 40, 50, 'OL008');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS039', 'SUB038', 'T008', 'B114', to_date('2021-03-04', 'YYYY-MM-DD'), to_date('2021-04-03', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 20, 40, 40, 'OL008');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS040', 'SUB039', 'T008', 'B115', to_date('2021-04-04', 'YYYY-MM-DD'), to_date('2021-05-30', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 20, 30, 50, 'OL008');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS041', 'SUB001', 'T001', 'B002', to_date('2021-02-10', 'YYYY-MM-DD'), to_date('2021-03-12', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 20, 40, 40, 'OL009');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS042', 'SUB006', 'T001', 'B016', to_date('2021-03-13', 'YYYY-MM-DD'), to_date('2021-04-12', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 30, 30, 40, 'OL009');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS043', 'SUB007', 'T001', 'B020', to_date('2021-04-13', 'YYYY-MM-DD'), to_date('2021-05-13', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 20, 40, 50, 'OL009');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS044', 'SUB010', 'T001', 'B030', to_date('2021-05-14', 'YYYY-MM-DD'), to_date('2021-06-13', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 20, 40, 40, 'OL009');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS045', 'SUB021', 'T001', 'B061', to_date('2021-06-14', 'YYYY-MM-DD'), to_date('2021-08-09', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 20, 30, 50, 'OL009');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS046', 'SUB021', 'T003', 'B061', to_date('2021-03-01', 'YYYY-MM-DD'), to_date('2021-03-31', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 40, 30, 30, 'OL010');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS047', 'SUB020', 'T003', 'B058', to_date('2021-04-01', 'YYYY-MM-DD'), to_date('2021-05-01', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 20, 40, 40, 'OL010');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS048', 'SUB034', 'T003', 'B103', to_date('2021-05-02', 'YYYY-MM-DD'), to_date('2021-06-01', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 30, 30, 40, 'OL010');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS049', 'SUB035', 'T003', 'B105', to_date('2021-06-02', 'YYYY-MM-DD'), to_date('2021-07-02', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 20, 40, 40, 'OL010');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS050', 'SUB037', 'T003', 'B110', to_date('2021-07-03', 'YYYY-MM-DD'), to_date('2021-08-28', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 20, 40, 40, 'OL010');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS051', 'SUB014', 'T006', 'B041', to_date('2021-03-01', 'YYYY-MM-DD'), to_date('2021-03-31', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 20, 40, 40, 'OL011');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS052', 'SUB029', 'T006', 'B086', to_date('2021-04-01', 'YYYY-MM-DD'), to_date('2021-05-01', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 30, 30, 40, 'OL011');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS053', 'SUB032', 'T006', 'B112', to_date('2021-05-02', 'YYYY-MM-DD'), to_date('2021-06-01', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 20, 50, 30, 'OL011');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS054', 'SUB033', 'T006', 'B007', to_date('2021-06-02', 'YYYY-MM-DD'), to_date('2021-07-02', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 20, 20, 60, 'OL011');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS055', 'SUB038', 'T006', 'B113', to_date('2021-07-03', 'YYYY-MM-DD'), to_date('2021-08-28', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 40, 40, 20, 'OL011');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS056', 'SUB001', 'T007', 'B003', to_date('2020-11-01', 'YYYY-MM-DD'), to_date('2020-12-01', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 20, 40, 40, 'OL012');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS057', 'SUB002', 'T007', 'B004', to_date('2020-12-02', 'YYYY-MM-DD'), to_date('2021-01-01', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 30, 30, 40, 'OL012');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS058', 'SUB014', 'T007', 'B040', to_date('2021-01-02', 'YYYY-MM-DD'), to_date('2021-02-01', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 20, 40, 50, 'OL012');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS059', 'SUB015', 'T007', 'B045', to_date('2021-02-02', 'YYYY-MM-DD'), to_date('2021-03-04', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 20, 40, 40, 'OL012');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS060', 'SUB016', 'T007', 'B047', to_date('2021-03-05', 'YYYY-MM-DD'), to_date('2021-04-30', 'YYYY-MM-DD'), '강의종료', 'Y', 'Y', 20, 30, 50, 'OL012');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS061', 'SUB001', 'T001', 'B003', to_date('2022-04-01', 'YYYY-MM-DD'), to_date('2022-05-01', 'YYYY-MM-DD'), '강의예정', 'N', 'N', 20, 40, 40, 'OL013');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS062', 'SUB002', 'T001', 'B006', to_date('2022-05-02', 'YYYY-MM-DD'), to_date('2022-06-01', 'YYYY-MM-DD'), '강의예정', 'N', 'N', 20, 30, 50, 'OL013');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS063', 'SUB007', 'T001', 'B020', to_date('2022-06-02', 'YYYY-MM-DD'), to_date('2022-07-02', 'YYYY-MM-DD'), '강의예정', 'N', 'N', 20, 30, 50, 'OL013');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS064', 'SUB013', 'T001', 'B037', to_date('2022-07-03', 'YYYY-MM-DD'), to_date('2022-08-02', 'YYYY-MM-DD'), '강의예정', 'N', 'N', 20, 30, 50, 'OL013');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS065', 'SUB034', 'T001', 'B101', to_date('2022-08-03', 'YYYY-MM-DD'), to_date('2022-09-28', 'YYYY-MM-DD'), '강의예정', 'N', 'N', 40, 30, 30, 'OL013');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS066', 'SUB002', 'T008', 'B006', to_date('2022-02-01', 'YYYY-MM-DD'), to_date('2022-03-03', 'YYYY-MM-DD'), '강의예정', 'N', 'N', 20, 40, 40, 'OL014');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS067', 'SUB040', 'T008', 'B121', to_date('2022-03-04', 'YYYY-MM-DD'), to_date('2022-04-03', 'YYYY-MM-DD'), '강의예정', 'N', 'N', 20, 30, 50, 'OL014');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS068', 'SUB008', 'T008', 'B026', to_date('2022-04-04', 'YYYY-MM-DD'), to_date('2022-05-04', 'YYYY-MM-DD'), '강의예정', 'N', 'N', 30, 30, 50, 'OL014');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS069', 'SUB009', 'T008', 'B027', to_date('2022-05-05', 'YYYY-MM-DD'), to_date('2022-06-04', 'YYYY-MM-DD'), '강의예정', 'N', 'N', 20, 30, 50, 'OL014');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS070', 'SUB023', 'T008', 'B068', to_date('2022-06-05', 'YYYY-MM-DD'), to_date('2022-07-31', 'YYYY-MM-DD'), '강의예정', 'N', 'N', 20, 30, 30, 'OL014');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS071', 'SUB008', 'T004', 'B024', to_date('2022-03-01', 'YYYY-MM-DD'), to_date('2022-03-31', 'YYYY-MM-DD'), '강의예정', 'N', 'N', 20, 40, 40, 'OL015');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS072', 'SUB009', 'T004', 'B026', to_date('2022-04-01', 'YYYY-MM-DD'), to_date('2022-05-01', 'YYYY-MM-DD'), '강의예정', 'N', 'N', 30, 30, 40, 'OL015');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS073', 'SUB020', 'T004', 'B058', to_date('2022-05-02', 'YYYY-MM-DD'), to_date('2022-06-01', 'YYYY-MM-DD'), '강의예정', 'N', 'N', 20, 40, 50, 'OL015');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS074', 'SUB033', 'T004', 'B098', to_date('2022-06-02', 'YYYY-MM-DD'), to_date('2022-07-02', 'YYYY-MM-DD'), '강의예정', 'N', 'N', 20, 40, 40, 'OL015');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS075', 'SUB013', 'T004', 'B039', to_date('2022-07-03', 'YYYY-MM-DD'), to_date('2022-08-28', 'YYYY-MM-DD'), '강의예정', 'N', 'N', 20, 30, 50, 'OL015');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS076', 'SUB001', 'T010', 'B003', to_date('2021-04-01', 'YYYY-MM-DD'), to_date('2021-05-01', 'YYYY-MM-DD'), '폐강', 'N', 'N', 20, 40, 40, 'OL016');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS077', 'SUB002', 'T010', 'B006', to_date('2021-05-02', 'YYYY-MM-DD'), to_date('2021-06-01', 'YYYY-MM-DD'), '폐강', 'N', 'N', 20, 30, 50, 'OL016');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS078', 'SUB033', 'T010', 'B099', to_date('2021-06-02', 'YYYY-MM-DD'), to_date('2021-07-02', 'YYYY-MM-DD'), '폐강', 'N', 'N', 20, 30, 50, 'OL016');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS079', 'SUB038', 'T010', 'B114', to_date('2021-07-03', 'YYYY-MM-DD'), to_date('2021-08-02', 'YYYY-MM-DD'), '폐강', 'N', 'N', 20, 30, 50, 'OL016');

INSERT INTO TBLOPENSUBJECT (OPEN_SUBJECT_SEQ, SUBJECT_SEQ, TEACHER_SEQ, TEXTBOOK_SEQ, SUBJECT_START_DATE, SUBJECT_END_DATE, SUBJECT_PROGRESS, SCORE_CHECK, TESTFILE_CHECK, ATTENDANCE_DISTRIBUTION, WRITTEN_DISTRIBUTION, PRACTICAL_DISTRIBUTION, OPEN_COURSE_SEQ) 
VALUES ('OS080', 'SUB023', 'T010', 'B067', to_date('2021-08-03', 'YYYY-MM-DD'), to_date('2021-09-28', 'YYYY-MM-DD'), '폐강', 'N', 'N', 40, 30, 30, 'OL016');


COMMIT;