SET DEFINE OFF

INSERT INTO TBLOPENCOURSE (OPEN_COURSE_SEQ, COURSE_SEQ, COURSE_START_DATE, COURSE_END_DATE, REG_OPEN_SUBJECT, COURSE_PROGRESS, CLASSROOM_SEQ) 
VALUES ('OL001', 'L001', to_date('2021-09-08', 'RRRR-MM-DD'), to_date('2022-03-07', 'RRRR-MM-DD'), 'Y', '강의중', 'R001');

INSERT INTO TBLOPENCOURSE (OPEN_COURSE_SEQ, COURSE_SEQ, COURSE_START_DATE, COURSE_END_DATE, REG_OPEN_SUBJECT, COURSE_PROGRESS, CLASSROOM_SEQ) 
VALUES ('OL002', 'L002', to_date('2021-08-01', 'RRRR-MM-DD'), to_date('2022-01-28', 'RRRR-MM-DD'), 'Y', '강의중', 'R002');

INSERT INTO TBLOPENCOURSE (OPEN_COURSE_SEQ, COURSE_SEQ, COURSE_START_DATE, COURSE_END_DATE, REG_OPEN_SUBJECT, COURSE_PROGRESS, CLASSROOM_SEQ) 
VALUES ('OL003', 'L003', to_date('2021-08-13', 'RRRR-MM-DD'), to_date('2022-02-09', 'RRRR-MM-DD'), 'Y', '강의중', 'R003');

INSERT INTO TBLOPENCOURSE (OPEN_COURSE_SEQ, COURSE_SEQ, COURSE_START_DATE, COURSE_END_DATE, REG_OPEN_SUBJECT, COURSE_PROGRESS, CLASSROOM_SEQ) 
VALUES ('OL004', 'L004', to_date('2021-09-01', 'RRRR-MM-DD'), to_date('2022-02-28', 'RRRR-MM-DD'), 'Y', '강의중', 'R004');

INSERT INTO TBLOPENCOURSE (OPEN_COURSE_SEQ, COURSE_SEQ, COURSE_START_DATE, COURSE_END_DATE, REG_OPEN_SUBJECT, COURSE_PROGRESS, CLASSROOM_SEQ) 
VALUES ('OL005', 'L017', to_date('2021-09-02', 'RRRR-MM-DD'), to_date('2022-03-01', 'RRRR-MM-DD'), 'Y', '강의중', 'R005');

INSERT INTO TBLOPENCOURSE (OPEN_COURSE_SEQ, COURSE_SEQ, COURSE_START_DATE, COURSE_END_DATE, REG_OPEN_SUBJECT, COURSE_PROGRESS, CLASSROOM_SEQ) 
VALUES ('OL006', 'L006', to_date('2021-09-03', 'RRRR-MM-DD'), to_date('2022-03-02', 'RRRR-MM-DD'), 'Y', '강의중', 'R006');

INSERT INTO TBLOPENCOURSE (OPEN_COURSE_SEQ, COURSE_SEQ, COURSE_START_DATE, COURSE_END_DATE, REG_OPEN_SUBJECT, COURSE_PROGRESS, CLASSROOM_SEQ) 
VALUES ('OL007', 'L007', to_date('2021-01-01', 'RRRR-MM-DD'), to_date('2021-06-30', 'RRRR-MM-DD'), 'Y', '강의종료', 'R001');

INSERT INTO TBLOPENCOURSE (OPEN_COURSE_SEQ, COURSE_SEQ, COURSE_START_DATE, COURSE_END_DATE, REG_OPEN_SUBJECT, COURSE_PROGRESS, CLASSROOM_SEQ) 
VALUES ('OL008', 'L005', to_date('2020-12-01', 'RRRR-MM-DD'), to_date('2021-05-30', 'RRRR-MM-DD'), 'Y', '강의종료', 'R002');

INSERT INTO TBLOPENCOURSE (OPEN_COURSE_SEQ, COURSE_SEQ, COURSE_START_DATE, COURSE_END_DATE, REG_OPEN_SUBJECT, COURSE_PROGRESS, CLASSROOM_SEQ) 
VALUES ('OL009', 'L001', to_date('2021-02-10', 'RRRR-MM-DD'), to_date('2021-08-09', 'RRRR-MM-DD'), 'Y', '강의종료', 'R003');

INSERT INTO TBLOPENCOURSE (OPEN_COURSE_SEQ, COURSE_SEQ, COURSE_START_DATE, COURSE_END_DATE, REG_OPEN_SUBJECT, COURSE_PROGRESS, CLASSROOM_SEQ) 
VALUES ('OL010', 'L010', to_date('2021-03-01', 'RRRR-MM-DD'), to_date('2021-08-28', 'RRRR-MM-DD'), 'Y', '강의종료', 'R004');

INSERT INTO TBLOPENCOURSE (OPEN_COURSE_SEQ, COURSE_SEQ, COURSE_START_DATE, COURSE_END_DATE, REG_OPEN_SUBJECT, COURSE_PROGRESS, CLASSROOM_SEQ) 
VALUES ('OL011', 'L011', to_date('2021-03-01', 'RRRR-MM-DD'), to_date('2021-08-28', 'RRRR-MM-DD'), 'Y', '강의종료', 'R005');

INSERT INTO TBLOPENCOURSE (OPEN_COURSE_SEQ, COURSE_SEQ, COURSE_START_DATE, COURSE_END_DATE, REG_OPEN_SUBJECT, COURSE_PROGRESS, CLASSROOM_SEQ) 
VALUES ('OL012', 'L003', to_date('2020-11-01', 'RRRR-MM-DD'), to_date('2021-04-30', 'RRRR-MM-DD'), 'Y', '강의종료', 'R006');

INSERT INTO TBLOPENCOURSE (OPEN_COURSE_SEQ, COURSE_SEQ, COURSE_START_DATE, COURSE_END_DATE, REG_OPEN_SUBJECT, COURSE_PROGRESS, CLASSROOM_SEQ) 
VALUES ('OL013', 'L013', to_date('2022-04-01', 'RRRR-MM-DD'), to_date('2022-09-28', 'RRRR-MM-DD'), 'Y', '강의예정', 'R001');

INSERT INTO TBLOPENCOURSE (OPEN_COURSE_SEQ, COURSE_SEQ, COURSE_START_DATE, COURSE_END_DATE, REG_OPEN_SUBJECT, COURSE_PROGRESS, CLASSROOM_SEQ) 
VALUES ('OL014', 'L014', to_date('2022-02-01', 'RRRR-MM-DD'), to_date('2022-07-31', 'RRRR-MM-DD'), 'Y', '강의예정', 'R002');

INSERT INTO TBLOPENCOURSE (OPEN_COURSE_SEQ, COURSE_SEQ, COURSE_START_DATE, COURSE_END_DATE, REG_OPEN_SUBJECT, COURSE_PROGRESS, CLASSROOM_SEQ) 
VALUES ('OL015', 'L012', to_date('2022-03-01', 'RRRR-MM-DD'), to_date('2022-08-28', 'RRRR-MM-DD'), 'Y', '강의예정', 'R003');

INSERT INTO TBLOPENCOURSE (OPEN_COURSE_SEQ, COURSE_SEQ, COURSE_START_DATE, COURSE_END_DATE, REG_OPEN_SUBJECT, COURSE_PROGRESS, CLASSROOM_SEQ) 
VALUES ('OL016', 'L016', to_date('2021-04-01', 'RRRR-MM-DD'), to_date('2021-09-28', 'RRRR-MM-DD'), 'Y', '폐강', 'R005');


commit;

