SET DEFINE OFF

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP001', '멀티미디어콘텐츠제작전문가');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP002', '사무자동화산업기사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP003', '전자계산기조직응용기사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP004', '정보관리기술사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP005', '정보기기운용기능사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP006', '정보처리기능사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP007', '정보처리기사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP008', '정보처리산업기사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP009', '컴퓨터시스템응용기술사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP010', '컴퓨터활용능력1급');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP011', '워드프로세서');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP012', '전산회계운용사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP013', '비서');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP014', '한글속기');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP015', '전자상거래관리사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP016', '컴퓨터활용능력2급');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP017', '전파전자통신기능사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP018', '통신선로기능사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP019', '무선설비기사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP020', '무선설비산업기사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP021', '무선설비기능사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP022', '무선통신사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP023', '아마추어 무선사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP024', '굴삭기운전기능사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP025', '지게차운전기능사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP026', '기중기운전기능사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP027', '로더운전기능사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP028', '롤러운전기능사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP029', '정보보안기사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP030', '게임그래픽전문가');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP031', '게임기획전문가');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP032', '게임프로그래밍전문가');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP033', '가맹거래사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP034', '감정평가사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP035', '건축사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP036', '경영지도사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP037', '경비지도사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP038', '공인노무사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP039', '공인중개사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP040', '공인회계사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP041', '관광통역안내사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP042', '관세사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP043', '교원 자격증');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP044', '교통안전관리자');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP045', '기술지도사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP046', '물류관리사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP047', '버스운전자격증');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP048', '법무사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP049', '변리사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP050', '변호사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP051', '보세사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP052', '보험계리사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP053', '세무사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP054', '사서');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP055', '사회복지사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP056', '소방안전관리자');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP057', '손해사정사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP058', '유통관리사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP059', '응급구조사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP060', '주택관리사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP061', '접골사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP062', '청소년상담사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP063', '청소년지도사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP064', '침사, 구사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP065', '큐레이터');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP066', '한국어 교원 자격증');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP067', '행정사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP068', '화물운송자격증');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP069', '네트워크관리사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP070', 'PC정비사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP071', '정보기술자격(ITQ)시험');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP072', 'PC Master(정비사)');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP073', '데이터아키텍처');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP074', 'SQL');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP075', 'ERP물류정보관리사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP076', 'ERP생산정보관리사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP077', 'ERP인사정보관리사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP078', 'ERP회계정보관리사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP079', '정보기술프로젝트관리전문가(IT-PMP)');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP080', 'RFID기술자격검정');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP081', 'IEQ(인터넷윤리자격)');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP082', 'IT+정보활용능력인증');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP083', '데이터분석');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP084', 'SW테스트전문가(CSTS)');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP085', 'TEPS(영어능력검정)');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP086', '한자실력급수');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP087', '한자·한문지도사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP088', '한자급수자격검정');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP089', '한국영어검정');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP090', '한국한자검정');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP091', 'FLEX 중국어(듣기/읽기)');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP092', 'FLEX 일본어(듣기/읽기)');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP093', 'FLEX 독일어(듣기/읽기)');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP094', 'FLEX 스페인어(듣기/읽기)');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP095', 'FLEX 프랑스어(듣기/읽기)');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP096', 'FLEX 영어(듣기/읽기)');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP097', 'FLEX 러시아어(듣기/읽기)');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP098', '상공회의소 한자');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP099', '한자어능력');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP100', '브레인트레이너');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP101', '실용수학');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP102', '무역영어');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP103', '샵마스터');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP104', '지역난방설비관리사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP105', 'CS Leaders(관리사)');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP106', 'GTQ(그래픽기술자격)');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP107', '시스템에어컨설계시공관리사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP108', 'SMAT(서비스경영자격)');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP109', '산업보안관리사');

INSERT INTO TBLLICENSE (LICENSE_SEQ, NAME) 
VALUES ('SP110', 'GTQi(그래픽기술자격일러스트)');

commit;
