SET DEFINE OFF

INSERT INTO TBLGIFT (GIFT_SEQ, NAME, PRICE) 
VALUES ('기념품번호', '기념품명', 가격);

INSERT INTO TBLGIFT (GIFT_SEQ, NAME, PRICE) 
VALUES ('GIFT01', 'CGU 영화 관람권', 10000);

INSERT INTO TBLGIFT (GIFT_SEQ, NAME, PRICE) 
VALUES ('GIFT02', 'MEGABAX 영화 관람권', 10000);

INSERT INTO TBLGIFT (GIFT_SEQ, NAME, PRICE) 
VALUES ('GIFT03', 'CINEMA 영화 관람권', 10000);

INSERT INTO TBLGIFT (GIFT_SEQ, NAME, PRICE) 
VALUES ('GIFT04', 'HYNDA 백화점 상품권', 10000);

INSERT INTO TBLGIFT (GIFT_SEQ, NAME, PRICE) 
VALUES ('GIFT05', '문화상품권 1만원정', 10000);

INSERT INTO TBLGIFT (GIFT_SEQ, NAME, PRICE) 
VALUES ('GIFT06', '문화상품권 5천원정', 5000);

INSERT INTO TBLGIFT (GIFT_SEQ, NAME, PRICE) 
VALUES ('GIFT07', '스다벅스 카페 금액권', 5000);

INSERT INTO TBLGIFT (GIFT_SEQ, NAME, PRICE) 
VALUES ('GIFT08', '이디요 카페 금액권', 5000);

INSERT INTO TBLGIFT (GIFT_SEQ, NAME, PRICE) 
VALUES ('GIFT09', 'GC25 편의점 금액권', 5000);

INSERT INTO TBLGIFT (GIFT_SEQ, NAME, PRICE) 
VALUES ('GIFT10', 'CV 편의점 금액권', 5000);

commit;