SET DEFINE OFF

INSERT INTO TBLATTENDANCETYPE (ATTENDANCE_TYPE_SEQ, ATTENDANCE_TYPE) 
VALUES ('TA01', '정상');

INSERT INTO TBLATTENDANCETYPE (ATTENDANCE_TYPE_SEQ, ATTENDANCE_TYPE) 
VALUES ('TA02', '지각');

INSERT INTO TBLATTENDANCETYPE (ATTENDANCE_TYPE_SEQ, ATTENDANCE_TYPE) 
VALUES ('TA03', '조퇴');

INSERT INTO TBLATTENDANCETYPE (ATTENDANCE_TYPE_SEQ, ATTENDANCE_TYPE) 
VALUES ('TA04', '외출');

INSERT INTO TBLATTENDANCETYPE (ATTENDANCE_TYPE_SEQ, ATTENDANCE_TYPE) 
VALUES ('TA05', '병가');

INSERT INTO TBLATTENDANCETYPE (ATTENDANCE_TYPE_SEQ, ATTENDANCE_TYPE) 
VALUES ('TA06', '기타');
