SET DEFINE OFF

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB001', 'Java', '공통');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB002', 'JavaScript', '공통');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB003', 'React', '선택');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB004', 'C#', '공통');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB005', 'C++', '선택');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB006', 'Oracle', '선택');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB007', 'MySQL', '선택');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB008', 'HTML', '공통');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB009', 'CSS', '공통');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB010', 'Hadoop', '선택');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB011', 'NGINX', '선택');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB012', 'Redis', '선택');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB013', 'Vue.js', '선택');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB014', 'Ruby', '선택');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB015', 'JQuery', '선택');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB016', 'Spring', '선택');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB017', 'Amazon S3', '선택');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB018', 'Amazon EC2', '선택');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB019', 'Amazon RDS', '선택');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB020', 'Python', '공통');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB021', 'JDBC', '공통');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB022', 'IOT', '선택');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB023', 'NodeJs', '선택');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB024', 'GraphQL', '선택');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB025', 'RESTful', '선택');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB026', 'TypeScript', '선택');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB027', 'GO', '선택');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB028', 'Django', '선택');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB029', 'Flask', '선택');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB030', 'FireBase', '선택');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB031', 'React Native', '선택');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB032', 'Flutter', '선택');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB033', 'Git', '공통');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB034', '데이터마이닝', '선택');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB035', '텍스트마이닝', '선택');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB036', '인공지능', '선택');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB037', '데이터시각화', '선택');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB038', '소프트웨어공학', '공통');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB039', '정보보안', '선택');

INSERT INTO TBLSUBJECT (SUBJECT_SEQ, NAME, TYPE) 
VALUES ('SUB040', 'UI디자인', '선택');

