SET DEFINE OFF

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB001', 'T001');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB002', 'T001');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB004', 'T001');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB008', 'T001');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB009', 'T001');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB020', 'T001');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB021', 'T001');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB033', 'T001');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB038', 'T001');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB006', 'T001');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB007', 'T001');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB010', 'T001');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB011', 'T001');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB012', 'T001');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB013', 'T001');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB014', 'T001');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB029', 'T001');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB030', 'T001');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB031', 'T001');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB032', 'T001');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB034', 'T001');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB001', 'T002');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB002', 'T002');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB004', 'T002');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB008', 'T002');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB009', 'T002');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB020', 'T002');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB021', 'T002');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB033', 'T002');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB038', 'T002');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB007', 'T002');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB010', 'T002');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB011', 'T002');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB012', 'T002');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB013', 'T002');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB014', 'T002');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB015', 'T002');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB016', 'T002');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB017', 'T002');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB018', 'T002');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB019', 'T002');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB022', 'T002');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB023', 'T002');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB001', 'T003');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB002', 'T003');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB004', 'T003');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB008', 'T003');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB009', 'T003');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB020', 'T003');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB021', 'T003');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB033', 'T003');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB038', 'T003');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB020', 'T003');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB023', 'T003');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB024', 'T003');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB025', 'T003');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB026', 'T003');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB027', 'T003');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB028', 'T003');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB029', 'T003');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB030', 'T003');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB031', 'T003');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB032', 'T003');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB034', 'T003');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB035', 'T003');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB036', 'T003');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB037', 'T003');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB039', 'T003');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB040', 'T003');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB001', 'T004');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB002', 'T004');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB004', 'T004');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB008', 'T004');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB009', 'T004');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB020', 'T004');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB021', 'T004');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB033', 'T004');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB038', 'T004');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB006', 'T004');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB007', 'T004');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB010', 'T004');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB011', 'T004');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB012', 'T004');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB013', 'T004');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB014', 'T004');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB015', 'T004');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB016', 'T004');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB017', 'T004');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB018', 'T004');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB019', 'T004');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB022', 'T004');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB023', 'T004');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB024', 'T004');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB025', 'T004');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB026', 'T004');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB027', 'T004');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB001', 'T005');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB002', 'T005');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB004', 'T005');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB008', 'T005');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB009', 'T005');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB020', 'T005');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB021', 'T005');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB033', 'T005');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB038', 'T005');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB003', 'T005');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB005', 'T005');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB006', 'T005');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB007', 'T005');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB010', 'T005');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB036', 'T005');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB012', 'T005');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB013', 'T005');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB014', 'T005');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB015', 'T005');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB016', 'T005');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB017', 'T005');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB018', 'T005');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB020', 'T005');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB022', 'T005');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB023', 'T005');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB024', 'T005');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB025', 'T005');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB026', 'T005');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB027', 'T005');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB001', 'T006');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB002', 'T006');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB004', 'T006');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB008', 'T006');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB009', 'T006');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB020', 'T006');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB021', 'T006');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB033', 'T006');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB038', 'T006');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB006', 'T006');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB007', 'T006');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB010', 'T006');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB011', 'T006');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB012', 'T006');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB013', 'T006');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB014', 'T006');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB029', 'T006');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB030', 'T006');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB031', 'T006');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB032', 'T006');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB034', 'T006');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB001', 'T007');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB002', 'T007');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB004', 'T007');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB008', 'T007');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB009', 'T007');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB020', 'T007');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB021', 'T007');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB033', 'T007');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB038', 'T007');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB007', 'T007');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB010', 'T007');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB011', 'T007');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB012', 'T007');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB013', 'T007');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB014', 'T007');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB015', 'T007');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB016', 'T007');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB017', 'T007');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB018', 'T007');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB019', 'T007');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB022', 'T007');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB023', 'T007');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB001', 'T008');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB002', 'T008');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB004', 'T008');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB008', 'T008');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB009', 'T008');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB020', 'T008');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB021', 'T008');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB033', 'T008');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB038', 'T008');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB022', 'T008');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB023', 'T008');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB024', 'T008');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB025', 'T008');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB026', 'T008');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB027', 'T008');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB028', 'T008');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB029', 'T008');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB030', 'T008');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB031', 'T008');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB032', 'T008');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB034', 'T008');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB035', 'T008');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB036', 'T008');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB037', 'T008');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB039', 'T008');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB040', 'T008');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB001', 'T009');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB002', 'T009');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB004', 'T009');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB008', 'T009');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB009', 'T009');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB020', 'T009');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB021', 'T009');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB033', 'T009');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB038', 'T009');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB006', 'T009');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB007', 'T009');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB010', 'T009');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB011', 'T009');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB012', 'T009');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB013', 'T009');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB014', 'T009');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB015', 'T009');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB016', 'T009');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB017', 'T009');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB018', 'T009');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB019', 'T009');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB022', 'T009');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB023', 'T009');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB024', 'T009');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB025', 'T009');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB026', 'T009');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB027', 'T009');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB001', 'T010');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB002', 'T010');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB004', 'T010');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB008', 'T010');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB009', 'T010');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB020', 'T010');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB021', 'T010');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB033', 'T010');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB038', 'T010');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB003', 'T010');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB005', 'T010');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB006', 'T010');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB007', 'T010');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB010', 'T010');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB011', 'T010');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB012', 'T010');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB013', 'T010');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB014', 'T010');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB015', 'T010');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB016', 'T010');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB017', 'T010');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB018', 'T010');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB019', 'T010');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB022', 'T010');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB023', 'T010');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB024', 'T010');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB025', 'T010');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB026', 'T010');

INSERT INTO TBLTEACHERSUBJECT (SUBJECT_SEQ, TEACHER_SEQ) 
VALUES ('SUB027', 'T010');


COMMIT;
