SET DEFINE OFF

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B001', 'Java의 정석', '21세기사');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B002', '혼자 공부하는 자바', '루비페이퍼');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B003', 'Do it! 자바 프로그래밍 입문', '이지스퍼블리싱');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B004', 'Learning PHP MySQL & JavaScript With jQuery CSS & HTML5', '웹액츄얼리코리아');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B005', 'Learning PHP MySQL JavaScript & CSS Second Edition 한국어판', '한빛미디어');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B006', 'javascript + css 필살기', '에이콘출판사');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B007', 'React.js/ 스프링 부트/ AWS로 배우는 웹 개발 101', '에이콘출판사');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B008', '초보자를 위한 리액트 200제 (React)', '정보문화사');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B009', '생활코딩! React 리액트 프로그래밍', '위키북스');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B010', '이것이 C#이다', '한빛미디어');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B011', '이펙티브 C#', '한빛미디어');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B012', 'C#으로 배우는 입문부터 4가지 게임 제작까지', '한빛미디어');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B013', '윤성우의 열혈 C++ 프로그래밍', '오렌지미디어');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B014', 'Do it! C++ 언어 입문', '이지스퍼블리싱');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B015', '혼자 연구하는 C/C++', '와우북스');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B016', '한번에 이해되는 Oracle SQL & PL/SQL', '디지털북스');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B017', '백견불여일타 JSP&Servlet : Oracle&Eclipse', '에이콘출판사');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B018', '실전 DB 모델링과 SQL for Oracle', '제우미디어');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B019', 'Real MySQL 8.0 (1권)', '위키북스');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B020', '이것이 MySQL이다', '한빛미디어');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B021', '업무에 바로 쓰는 SQL 튜닝', '한빛미디어');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B022', 'HTML & CSS for Beginner', '에이콘출판사');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B023', '바로바로 HTML5', '제이펍');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B024', 'HTML5 캔버스', '에이콘출판사');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B025', '쉽고 빠르게 익히는 CSS 3', '인사이트(insight)');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B026', '웹 표준 핵심 가이드북 XHTML+CSS', '프리렉');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B027', 'CSS 비밀 매뉴얼', '제우미디어');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B028', 'Hadoop 보안', '에이콘출판사');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B029', 'Hadoop과 Solr를 이용한 기업용 검색 시스템 구축', '에이콘출판사');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B030', 'Hadoop 에코시스템', '에이콘출판사');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B031', 'NGINX 쿡북', '한빛미디어');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B032', 'Nginx HTTP 서버', '에이콘출판사');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B033', 'Nginx HTTP Server 한국어판', '에이콘출판사');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B034', '빅데이터 저장 및 분석을 위한 NoSQL & Redis', '데이터북');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B035', 'Redis와 Node.js를 사용한 웹 애플리케이션 개발', '한빛미디어');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B036', 'Redis 운영 관리', '에이콘출판사');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B037', '한 권으로 배우는 Vue.js 3', '영진닷컴');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B038', 'Do it! Vue.js 입문', '이지스퍼블리싱');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B039', 'Vue.js 프로젝트 투입 일주일 전', '비제이퍼블릭(BJ퍼블릭)');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B040', '프로그래밍 루비', '인사이트(insight)');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B041', '루비 프로그래밍 언어', '생능출판사');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B042', '독하게 시작하는 루비 프로그래밍', '한빛미디어');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B043', 'Head First jQuery', '에이콘출판사');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B044', 'jQuery로 만드는 모바일 & 웹 게임', '한빛미디어');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B045', 'jQuery Mobile First Look', '에이콘출판사');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B046', '스프링 부트와 AWS로 혼자 구현하는 웹 서비스', '프리렉');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B047', '스프링 부트 쇼핑몰 프로젝트 with JPA', '로드북');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B048', '스프링 부트 실전 활용 마스터', '책만');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B049', '아마존 웹 서비스(AWS)로 시작하는 데브옵스', '정보문화사');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B050', '배워서 바로 쓰는 14가지 AWS 구축 패턴', '한빛미디어');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B051', 'Amazon Redshift', '에이콘출판사');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B052', '아마존 웹 서비스 부하 테스트 입문', '제이펍');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B053', '아마존 웹 서비스 클라우드 디자인 패턴 설계 가이드', '제이펍');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B054', '아마존 웹 서비스 인 액션', '한빛미디어');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B055', '아마존 웹 서비스를 다루는 기술', '길벗');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B056', '클라우드 핀옵스', '한빛미디어');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B057', 'AWS 침투 테스트', '에이콘출판사');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B058', 'Do it! 점프 투 파이썬', '이지스퍼블리싱');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B059', '혼자 공부하는 머신러닝+딥러닝', '한빛미디어');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B060', '혼자 공부하는 파이썬', '한빛미디어');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B061', 'JDBC API를 이용한 데이터베이스 프로그래밍', '한국학술정보');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B062', '마이바티스 프로그래밍', '에이콘출판사');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B063', 'ORACLE-JDBC & JSP PROGRAMMING', '네오솔루션');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B064', '앱인벤터를 활용한 IOT 빅데이터 기반의 모바일앱 개발', '에듀컨텐츠휴피아');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B065', '그림으로배우는 서버구조', '영진닷컴');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B066', 'IOT 사물인터넷을 위한 라즈베리파이 4', '앤써북');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B067', 'Node.js 교과서', '길벗');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B068', 'Nodejs 디자인 패턴 바이블', '영진닷컴');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B069', '백견불여일타 Node.js 로 서버 만들기', '로드북');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B070', '웹 앱 API 개발을 위한 GraphQL', '인사이트');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B071', 'GraphQL Eine Einfuehrung in APIs mit GraphQL', 'O''Reilly Media');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B072', 'Graphql in Action', 'Manning Publications');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B073', 'RESTful 파이썬 웹 서비스 제작', '에이콘출판');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B074', 'RESTful 자바 패턴과 실전 응용', '에이콘출판');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B075', 'RESTful 자바 웹 서비스 보안', '에이콘출판');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B076', '이펙티브 타입스크립트', '인사이트');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B077', 'Angular Development with TypeScript', '루비페이퍼');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B078', 'Programming Typescript', 'O''Reilly Media');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B079', 'Tucker의 Go 언어 프로그래밍', '골든래빗(주)');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B080', 'Go 마스터하기', '에이콘출판');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B081', '밑바닥부터 만드는 인터프리터 in Go', '인사이트');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B082', 'AWS 클라우드 기반의 Django 웹 애플리케이션', '디지털북스');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B083', 'Django 한 그릇 뚝딱', '비제이퍼블릭');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B084', 'Django(장고)로 쉽게 배우는 배프의 오지랖 파이썬 웹프로그래밍', '디지털북스');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B085', 'Flask 기반의 파이썬 웹 프로그래밍', '제이펍');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B086', 'Do it! 점프 투 플라스크', '이지스퍼블리싱');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B087', '처음 배우는 플라스크 웹 프로그래밍', '한빛미디어');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B088', '백견불여일타 파이어베이스', '로드북');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B089', 'FireBase로 안드로이드 SNS 앱 만들기', '비제이퍼블릭');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B090', 'Do it! 파이어베이스 프로그래밍', '이지스퍼블리싱');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B091', '리액트 네이티브를 다루는 기술', '길벗');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B092', '처음 배우는 리액트 네이티브', '한빛미디어');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B093', 'Do it! 리액트 네이티브 앱 프로그래밍', '이지스퍼블리싱');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B094', 'Do it! 플러터 앱 프로그래밍', '이지스퍼블리싱');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B095', '모두가 할 수 있는 플러터UI입문', '앤써북');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B096', '오준석의 플러터 생존 코딩', '한빛미디어');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B097', '팀 개발을 위한 Git - GitHub 시작하기', '한빛미디어');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B098', 'Do it! 지옥에서 온 문서 관리자 깃&깃허브 입문', '이지스퍼블리싱');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B099', '프로 Git 2판', '인사이트');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B100', '데이터마이닝 기법과 응용', '한나래');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B101', '데이터마이닝 R', '이앤비플러스');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B102', 'R 데이터마이닝', '자유아카데미');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B103', 'R 비즈니스 데이터 분석과 텍스트마이닝', '한나래아카데미');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B104', 'Do it! 쉽게 배우는 R 텍스트 마이닝', '이지스퍼블리싱');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B105', '잡아라! 텍스트 마이닝 with 파이썬', '비제이퍼블릭');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B106', '혼자 공부하는 머신러닝 + 딥러닝', '한빛미디어');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B107', '모두의 인공지능 기초 수학', '길벗');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B108', '모두의 인공지능 with 파이썬', '길벗');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B109', '데이터 시각화 교과서', '책만');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B110', '데이터시각화', '한국방송통신대학교출판문화원');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B111', '대시보드 설계와 데이터 시각화', '책만');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B112', '한 권으로 읽는 컴퓨터 구조와 프로그래밍', '책만');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B113', '소프트웨어공학', '한티미디어');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B114', '소프트웨어공학', '한국방송통신대학교출판문화원');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B115', '정보보안개론', '인피니티북스');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B116', 'IT정보보안 전문가가 되는 길', 'BOOKK(부크크)');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B117', '정보보안 이론과 실제', '한빛아카데미');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B118', '모바일 UX/UI 디자인 강의 with Adobe XD', '한빛미디어');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B119', '이것이 UX/UI 디자인이다', '위키북스');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B120', 'UI/UX 디자인 이론과 실습 with Adobe XD', '한빛아카데미');

INSERT INTO TBLTEXTBOOK (TEXTBOOK_SEQ, NAME, PUBLISHER) 
VALUES ('B121', '모바일 UI/UX 디자인 실무', '한빛아카데미');

commit;

