SET DEFINE OFF

INSERT INTO TBLCLASSROOM (CLASSROOM_SEQ, NAME, CAPACITY) 
VALUES ('R001', '1강의실', 30);

INSERT INTO TBLCLASSROOM (CLASSROOM_SEQ, NAME, CAPACITY) 
VALUES ('R002', '2강의실', 30);

INSERT INTO TBLCLASSROOM (CLASSROOM_SEQ, NAME, CAPACITY) 
VALUES ('R003', '3강의실', 30);

INSERT INTO TBLCLASSROOM (CLASSROOM_SEQ, NAME, CAPACITY) 
VALUES ('R004', '4강의실', 26);

INSERT INTO TBLCLASSROOM (CLASSROOM_SEQ, NAME, CAPACITY) 
VALUES ('R005', '5강의실', 26);

INSERT INTO TBLCLASSROOM (CLASSROOM_SEQ, NAME, CAPACITY) 
VALUES ('R006', '6강의실', 26);

commit;