SET DEFINE OFF

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0381', 'OL001', '부산광역시', 2000, 3000, '고졸', 'N', NULL, 'RE0001', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0411', 'OL001', '경기도', 2100, 3300, '대졸', 'N', NULL, 'RE0002', 'TASK002');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0133', 'OL001', '강원도', 2800, 3100, '초대졸', 'N', NULL, 'RE0003', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0286', 'OL001', '경기도', 2400, 3700, '고졸', 'N', NULL, 'RE0004', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0358', 'OL001', '광주광역시', 2300, 3500, '초대졸', 'N', NULL, 'RE0005', 'TASK002');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0315', 'OL001', '경기도', 2100, 3300, '고졸', 'N', NULL, 'RE0006', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0308', 'OL001', '서울특별시', 2600, 3500, '고졸', 'N', NULL, 'RE0007', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0417', 'OL001', '강원도', 2800, 3000, '초대졸', 'N', NULL, 'RE0008', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0307', 'OL001', '부산광역시', 2300, 3400, '대졸', 'N', NULL, 'RE0009', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0249', 'OL001', '경기도', 2800, 3100, '대졸', 'N', NULL, 'RE0010', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0138', 'OL001', '광주광역시', 2600, 3500, '고졸', 'N', NULL, 'RE0011', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0183', 'OL001', '강원도', 2700, 3000, '대졸', 'N', NULL, 'RE0012', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0416', 'OL001', '서울특별시', 2800, 3600, '고졸', 'N', NULL, 'RE0013', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0300', 'OL001', '서울특별시', 2000, 3600, '초대졸', 'N', NULL, 'RE0015', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0468', 'OL001', '제주특별자치도', 2700, 3700, '대졸', 'N', NULL, 'RE0016', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0038', 'OL001', '부산광역시', 2100, 3000, '대졸', 'N', NULL, 'RE0017', 'TASK004');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0013', 'OL001', '경기도', 2200, 3200, '고졸', 'N', NULL, 'RE0018', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0171', 'OL001', '제주특별자치도', 2500, 3500, '고졸', 'N', NULL, 'RE0019', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0473', 'OL001', '광주광역시', 2500, 3500, '대졸', 'N', NULL, 'RE0020', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0004', 'OL001', '제주특별자치도', 2200, 3600, '대졸', 'N', NULL, 'RE0021', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0035', 'OL001', '서울특별시', 2100, 3700, '대졸', 'N', NULL, 'RE0022', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0276', 'OL001', '강원도', 2700, 3800, '초대졸', 'N', NULL, 'RE0023', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0294', 'OL001', '부산광역시', 2500, 3300, '대졸', 'N', NULL, 'RE0024', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0160', 'OL001', '경기도', 2000, 3800, '고졸', 'N', NULL, 'RE0025', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0152', 'OL001', '서울특별시', 2100, 3600, '대졸', 'N', NULL, 'RE0026', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0007', 'OL001', '광주광역시', 2400, 3100, '초대졸', 'N', NULL, 'RE0027', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0066', 'OL001', '서울특별시', 2500, 3300, '고졸', 'N', NULL, 'RE0028', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0497', 'OL001', '경기도', 2700, 3100, '대졸', 'N', NULL, 'RE0029', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0392', 'OL001', '제주특별자치도', 2300, 3000, '초대졸', 'N', NULL, 'RE0030', 'TASK005');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0218', 'OL002', '서울특별시', 2100, 3600, '고졸', 'N', NULL, 'RE0034', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0397', 'OL002', '강원도', 2500, 3100, '대졸', 'N', NULL, 'RE0035', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0177', 'OL002', '경기도', 2300, 3300, '고졸', 'N', NULL, 'RE0001', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0303', 'OL002', '제주특별자치도', 2800, 3700, '고졸', 'N', NULL, 'RE0002', 'TASK002');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0141', 'OL002', '서울특별시', 2700, 3400, '초대졸', 'N', NULL, 'RE0003', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0426', 'OL002', '강원도', 2200, 3600, '초대졸', 'N', NULL, 'RE0004', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0410', 'OL002', '서울특별시', 2300, 3500, '대졸', 'N', NULL, 'RE0005', 'TASK002');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0479', 'OL002', '서울특별시', 2300, 3800, '대졸', 'N', NULL, 'RE0006', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0284', 'OL002', '강원도', 2300, 3200, '고졸', 'N', NULL, 'RE0007', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0258', 'OL002', '경기도', 2200, 3400, '초대졸', 'N', NULL, 'RE0008', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0305', 'OL002', '강원도', 2100, 3600, '대졸', 'N', NULL, 'RE0009', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0487', 'OL002', '서울특별시', 2300, 3200, '초대졸', 'N', NULL, 'RE0010', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0465', 'OL002', '경기도', 2800, 3500, '초대졸', 'N', NULL, 'RE0011', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0071', 'OL002', '경기도', 2200, 3100, '초대졸', 'N', NULL, 'RE0012', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0467', 'OL002', '강원도', 2600, 3500, '대졸', 'N', NULL, 'RE0013', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0084', 'OL002', '경기도', 2600, 3100, '대졸', 'N', NULL, 'RE0014', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0168', 'OL002', '경기도', 2200, 3600, '고졸', 'N', NULL, 'RE0015', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0231', 'OL002', '광주광역시', 2200, 3000, '고졸', 'N', NULL, 'RE0016', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0002', 'OL002', '강원도', 2400, 3400, '대졸', 'N', NULL, 'RE0017', 'TASK004');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0309', 'OL002', '부산광역시', 2000, 3100, '대졸', 'N', NULL, 'RE0018', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0268', 'OL002', '광주광역시', 2500, 3200, '고졸', 'N', NULL, 'RE0019', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0328', 'OL002', '광주광역시', 2600, 3600, '고졸', 'N', NULL, 'RE0020', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0014', 'OL002', '부산광역시', 2200, 3500, '초대졸', 'N', NULL, 'RE0021', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0033', 'OL002', '제주특별자치도', 2200, 3100, '대졸', 'N', NULL, 'RE0022', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0275', 'OL002', '부산광역시', 2400, 3100, '대졸', 'N', NULL, 'RE0023', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0481', 'OL002', '서울특별시', 2600, 3800, '대졸', 'N', NULL, 'RE0024', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0086', 'OL002', '제주특별자치도', 2500, 3600, '고졸', 'N', NULL, 'RE0025', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0389', 'OL003', '부산광역시', 2400, 3200, '고졸', 'N', NULL, 'RE0029', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0137', 'OL003', '광주광역시', 2300, 3600, '대졸', 'N', NULL, 'RE0030', 'TASK005');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0429', 'OL003', '서울특별시', 2000, 3000, '대졸', 'N', NULL, 'RE0031', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0001', 'OL003', '경기도', 2300, 3200, '대졸', 'N', NULL, 'RE0032', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0451', 'OL003', '강원도', 2100, 3700, '초대졸', 'N', NULL, 'RE0033', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0344', 'OL003', '광주광역시', 2400, 3700, '초대졸', 'N', NULL, 'RE0034', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0132', 'OL003', '서울특별시', 2200, 3700, '대졸', 'N', NULL, 'RE0035', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0082', 'OL003', '제주특별자치도', 2000, 3700, '고졸', 'N', NULL, 'RE0001', 'TASK002');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0407', 'OL003', '서울특별시', 2800, 3700, '초대졸', 'N', NULL, 'RE0002', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0352', 'OL003', '광주광역시', 2700, 3500, '대졸', 'N', NULL, 'RE0003', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0471', 'OL003', '경기도', 2700, 3000, '대졸', 'N', NULL, 'RE0004', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0018', 'OL003', '제주특별자치도', 2000, 3600, '고졸', 'N', NULL, 'RE0005', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0270', 'OL003', '광주광역시', 2700, 3700, '대졸', 'N', NULL, 'RE0006', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0441', 'OL003', '광주광역시', 2200, 3500, '대졸', 'N', NULL, 'RE0007', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0125', 'OL003', '제주특별자치도', 2600, 3400, '초대졸', 'N', NULL, 'RE0008', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0158', 'OL003', '부산광역시', 2000, 3700, '초대졸', 'N', NULL, 'RE0009', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0079', 'OL003', '서울특별시', 2600, 3200, '초대졸', 'N', NULL, 'RE0010', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0126', 'OL003', '경기도', 2200, 3700, '대졸', 'N', NULL, 'RE0011', 'TASK004');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0304', 'OL003', '서울특별시', 2700, 3600, '고졸', 'N', NULL, 'RE0012', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0107', 'OL003', '경기도', 2700, 3600, '대졸', 'N', NULL, 'RE0013', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0292', 'OL003', '경기도', 2500, 3100, '고졸', 'N', NULL, 'RE0014', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0310', 'OL003', '강원도', 2300, 3100, '대졸', 'N', NULL, 'RE0015', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0472', 'OL003', '부산광역시', 2300, 3400, '고졸', 'N', NULL, 'RE0016', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0099', 'OL003', '서울특별시', 2200, 3600, '대졸', 'N', NULL, 'RE0017', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0104', 'OL003', '서울특별시', 2400, 3400, '고졸', 'N', NULL, 'RE0018', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0419', 'OL003', '서울특별시', 2800, 3400, '고졸', 'N', NULL, 'RE0019', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0431', 'OL003', '경기도', 2600, 3400, '고졸', 'N', NULL, 'RE0020', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0163', 'OL004', '강원도', 2600, 3500, '대졸', 'N', NULL, 'RE0021', 'TASK005');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0030', 'OL004', '서울특별시', 2300, 3500, '대졸', 'N', NULL, 'RE0022', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0385', 'OL004', '광주광역시', 2700, 3600, '대졸', 'N', NULL, 'RE0023', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0096', 'OL004', '강원도', 2800, 3700, '초대졸', 'N', NULL, 'RE0024', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0463', 'OL004', '광주광역시', 2300, 3700, '초대졸', 'N', NULL, 'RE0025', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0390', 'OL004', '부산광역시', 2000, 3100, '고졸', 'N', NULL, 'RE0026', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0209', 'OL004', '서울특별시', 2200, 3100, '고졸', 'N', NULL, 'RE0027', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0029', 'OL004', '광주광역시', 2000, 3600, '고졸', 'N', NULL, 'RE0028', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0069', 'OL004', '제주특별자치도', 2300, 3700, '대졸', 'N', NULL, 'RE0029', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0448', 'OL004', '강원도', 2700, 3500, '대졸', 'N', NULL, 'RE0030', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0170', 'OL004', '강원도', 2600, 3100, '대졸', 'N', NULL, 'RE0031', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0380', 'OL004', '제주특별자치도', 2300, 3500, '대졸', 'N', NULL, 'RE0032', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0148', 'OL004', '광주광역시', 2100, 3600, '대졸', 'N', NULL, 'RE0033', 'TASK004');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0179', 'OL004', '광주광역시', 2300, 3200, '대졸', 'N', NULL, 'RE0034', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0227', 'OL004', '부산광역시', 2800, 3100, '초대졸', 'N', NULL, 'RE0035', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0361', 'OL004', '제주특별자치도', 2300, 3300, '대졸', 'N', NULL, 'RE0001', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0193', 'OL004', '경기도', 2000, 3800, '고졸', 'N', NULL, 'RE0002', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0025', 'OL004', '제주특별자치도', 2000, 3800, '초대졸', 'N', NULL, 'RE0003', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0399', 'OL004', '광주광역시', 2200, 3200, '초대졸', 'N', NULL, 'RE0004', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0427', 'OL004', '광주광역시', 2200, 3800, '고졸', 'N', NULL, 'RE0005', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0306', 'OL004', '강원도', 2300, 3000, '고졸', 'N', NULL, 'RE0006', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0077', 'OL004', '강원도', 2300, 3300, '초대졸', 'N', NULL, 'RE0007', 'TASK005');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0271', 'OL004', '서울특별시', 2700, 3800, '고졸', 'N', NULL, 'RE0008', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0256', 'OL004', '부산광역시', 2500, 3300, '초대졸', 'N', NULL, 'RE0009', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0197', 'OL004', '제주특별자치도', 2300, 3700, '대졸', 'N', NULL, 'RE0010', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0374', 'OL004', '제주특별자치도', 2000, 3600, '대졸', 'N', NULL, 'RE0011', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0330', 'OL005', '부산광역시', 2500, 3000, '고졸', 'N', NULL, 'RE0013', 'TASK002');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0348', 'OL005', '경기도', 2700, 3400, '초대졸', 'N', NULL, 'RE0014', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0093', 'OL005', '경기도', 2100, 3000, '초대졸', 'N', NULL, 'RE0015', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0289', 'OL005', '서울특별시', 2200, 3200, '고졸', 'N', NULL, 'RE0016', 'TASK002');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0295', 'OL005', '경기도', 2200, 3700, '대졸', 'N', NULL, 'RE0017', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0100', 'OL005', '광주광역시', 2200, 3300, '대졸', 'N', NULL, 'RE0018', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0111', 'OL005', '강원도', 2300, 3800, '초대졸', 'N', NULL, 'RE0019', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0220', 'OL005', '강원도', 2600, 3700, '초대졸', 'N', NULL, 'RE0020', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0298', 'OL005', '제주특별자치도', 2200, 3300, '초대졸', 'N', NULL, 'RE0021', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0080', 'OL005', '경기도', 2200, 3000, '대졸', 'N', NULL, 'RE0022', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0254', 'OL005', '광주광역시', 2600, 3700, '고졸', 'N', NULL, 'RE0023', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0456', 'OL005', '부산광역시', 2800, 3300, '대졸', 'N', NULL, 'RE0024', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0280', 'OL005', '광주광역시', 2000, 3700, '대졸', 'N', NULL, 'RE0025', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0009', 'OL005', '제주특별자치도', 2100, 3700, '대졸', 'N', NULL, 'RE0026', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0151', 'OL005', '제주특별자치도', 2100, 3800, '대졸', 'N', NULL, 'RE0027', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0322', 'OL005', '제주특별자치도', 2800, 3100, '고졸', 'N', NULL, 'RE0028', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0321', 'OL005', '광주광역시', 2500, 3600, '초대졸', 'N', NULL, 'RE0029', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0482', 'OL005', '부산광역시', 2200, 3600, '고졸', 'N', NULL, 'RE0030', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0150', 'OL005', '부산광역시', 2100, 3000, '초대졸', 'N', NULL, 'RE0031', 'TASK005');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0387', 'OL005', '서울특별시', 2200, 3200, '대졸', 'N', NULL, 'RE0032', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0169', 'OL005', '부산광역시', 2700, 3300, '고졸', 'N', NULL, 'RE0033', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0012', 'OL005', '부산광역시', 2800, 3300, '대졸', 'N', NULL, 'RE0034', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0302', 'OL005', '광주광역시', 2200, 3800, '대졸', 'N', NULL, 'RE0035', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0087', 'OL005', '경기도', 2600, 3300, '대졸', 'N', NULL, 'RE0001', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0175', 'OL005', '강원도', 2700, 3300, '대졸', 'N', NULL, 'RE0002', 'TASK002');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0110', 'OL006', '광주광역시', 2100, 3100, '대졸', 'N', NULL, 'RE0003', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0207', 'OL006', '부산광역시', 2800, 3600, '대졸', 'N', NULL, 'RE0004', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0440', 'OL006', '강원도', 2100, 3000, '초대졸', 'N', NULL, 'RE0005', 'TASK002');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0136', 'OL006', '경기도', 2000, 3500, '대졸', 'N', NULL, 'RE0006', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0173', 'OL006', '경기도', 2100, 3500, '대졸', 'N', NULL, 'RE0007', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0312', 'OL006', '서울특별시', 2100, 3700, '대졸', 'N', NULL, 'RE0008', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0241', 'OL006', '제주특별자치도', 2700, 3400, '대졸', 'N', NULL, 'RE0009', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0041', 'OL006', '경기도', 2100, 3000, '대졸', 'N', NULL, 'RE0010', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0147', 'OL006', '부산광역시', 2300, 3400, '초대졸', 'N', NULL, 'RE0011', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0283', 'OL006', '서울특별시', 2700, 3800, '초대졸', 'N', NULL, 'RE0012', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0401', 'OL006', '광주광역시', 2800, 3600, '대졸', 'N', NULL, 'RE0013', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0078', 'OL006', '광주광역시', 2800, 3200, '고졸', 'N', NULL, 'RE0014', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0439', 'OL006', '경기도', 2400, 3500, '대졸', 'N', NULL, 'RE0015', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0461', 'OL006', '광주광역시', 2800, 3600, '고졸', 'N', NULL, 'RE0016', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0043', 'OL006', '부산광역시', 2100, 3200, '고졸', 'N', NULL, 'RE0017', 'TASK004');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0432', 'OL006', '강원도', 2300, 3300, '고졸', 'N', NULL, 'RE0018', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0117', 'OL006', '광주광역시', 2100, 3000, '대졸', 'N', NULL, 'RE0019', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0118', 'OL006', '강원도', 2500, 3200, '고졸', 'N', NULL, 'RE0020', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0316', 'OL006', '광주광역시', 2300, 3500, '고졸', 'N', NULL, 'RE0021', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0055', 'OL006', '부산광역시', 2300, 3700, '대졸', 'N', NULL, 'RE0022', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0496', 'OL006', '광주광역시', 2700, 3400, '대졸', 'N', NULL, 'RE0023', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0194', 'OL006', '제주특별자치도', 2400, 3200, '대졸', 'N', NULL, 'RE0024', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0403', 'OL006', '광주광역시', 2300, 3700, '초대졸', 'N', NULL, 'RE0025', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0108', 'OL006', '강원도', 2100, 3200, '대졸', 'N', NULL, 'RE0026', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0262', 'OL006', '강원도', 2600, 3800, '대졸', 'N', NULL, 'RE0027', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0089', 'OL006', '제주특별자치도', 2500, 3500, '초대졸', 'N', NULL, 'RE0028', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0042', 'OL007', '서울특별시', 2700, 3700, '고졸', 'Y', to_date('2021-06-12', 'YYYY-MM-DD'), 'RE0037', 'TASK002');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0250', 'OL007', '서울특별시', 2100, 3100, '대졸', 'Y', to_date('2021-07-15', 'YYYY-MM-DD'), 'RE0038', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0057', 'OL007', '서울특별시', 2500, 3700, '대졸', 'Y', to_date('2021-08-20', 'YYYY-MM-DD'), 'RE0039', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0083', 'OL007', '경기도', 2100, 3300, '초대졸', 'Y', to_date('2021-08-16', 'YYYY-MM-DD'), 'RE0040', 'TASK002');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0415', 'OL007', '서울특별시', 2200, 3600, '고졸', 'Y', to_date('2021-06-29', 'YYYY-MM-DD'), 'RE0041', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0488', 'OL007', '서울특별시', 2100, 3000, '대졸', 'Y', to_date('2021-08-11', 'YYYY-MM-DD'), 'RE0042', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0076', 'OL007', '서울특별시', 2500, 3000, '대졸', 'N', NULL, 'RE0043', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0222', 'OL007', '광주광역시', 2000, 3000, '초대졸', 'Y', to_date('2021-08-18', 'YYYY-MM-DD'), 'RE0044', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0213', 'OL007', '부산광역시', 2300, 3000, '고졸', 'Y', to_date('2021-07-11', 'YYYY-MM-DD'), 'RE0045', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0116', 'OL007', '경기도', 2100, 3800, '고졸', 'Y', to_date('2021-06-22', 'YYYY-MM-DD'), 'RE0046', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0366', 'OL007', '경기도', 2700, 3700, '고졸', 'Y', to_date('2021-07-19', 'YYYY-MM-DD'), 'RE0047', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0225', 'OL007', '부산광역시', 2300, 3300, '대졸', 'Y', to_date('2021-08-12', 'YYYY-MM-DD'), 'RE0048', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0145', 'OL007', '경기도', 2600, 3100, '대졸', 'N', NULL, 'RE0049', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0003', 'OL007', '광주광역시', 2100, 3100, '대졸', 'Y', to_date('2021-06-09', 'YYYY-MM-DD'), 'RE0036', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0273', 'OL007', '서울특별시', 2100, 3000, '초대졸', 'Y', to_date('2021-07-30', 'YYYY-MM-DD'), 'RE0037', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0109', 'OL007', '서울특별시', 2400, 3400, '대졸', 'Y', to_date('2021-08-10', 'YYYY-MM-DD'), 'RE0038', 'TASK004');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0212', 'OL007', '강원도', 2300, 3600, '고졸', 'Y', to_date('2021-08-19', 'YYYY-MM-DD'), 'RE0039', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0293', 'OL007', '경기도', 2200, 3000, '대졸', 'Y', to_date('2021-06-22', 'YYYY-MM-DD'), 'RE0040', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0354', 'OL007', '제주특별자치도', 2000, 3200, '초대졸', 'Y', to_date('2021-06-10', 'YYYY-MM-DD'), 'RE0041', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0092', 'OL007', '강원도', 2600, 3300, '고졸', 'N', NULL, 'RE0042', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0336', 'OL007', '경기도', 2100, 3300, '대졸', 'Y', to_date('2021-06-24', 'YYYY-MM-DD'), 'RE0043', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0059', 'OL007', '서울특별시', 2300, 3200, '초대졸', 'Y', to_date('2021-08-01', 'YYYY-MM-DD'), 'RE0044', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0164', 'OL007', '제주특별자치도', 2600, 3100, '고졸', 'Y', to_date('2021-08-10', 'YYYY-MM-DD'), 'RE0045', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0332', 'OL007', '서울특별시', 2800, 3600, '고졸', 'Y', to_date('2021-08-18', 'YYYY-MM-DD'), 'RE0046', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0350', 'OL007', '서울특별시', 2000, 3600, '초대졸', 'Y', to_date('2021-08-24', 'YYYY-MM-DD'), 'RE0047', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0049', 'OL007', '부산광역시', 2800, 3500, '대졸', 'N', NULL, 'RE0048', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0236', 'OL007', '부산광역시', 2200, 3700, '초대졸', 'N', NULL, 'RE0049', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0425', 'OL007', '제주특별자치도', 2300, 3100, '고졸', 'N', NULL, 'RE0036', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0474', 'OL008', '부산광역시', 2800, 3600, '대졸', 'Y', to_date('2021-05-28', 'YYYY-MM-DD'), 'RE0037', 'TASK005');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0097', 'OL008', '부산광역시', 2800, 3600, '대졸', 'Y', to_date('2021-07-15', 'YYYY-MM-DD'), 'RE0038', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0045', 'OL008', '부산광역시', 2300, 3000, '대졸', 'Y', to_date('2021-06-07', 'YYYY-MM-DD'), 'RE0039', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0395', 'OL008', '강원도', 2300, 3400, '고졸', 'Y', to_date('2021-05-03', 'YYYY-MM-DD'), 'RE0040', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0378', 'OL008', '제주특별자치도', 2400, 3700, '초대졸', 'Y', to_date('2021-06-15', 'YYYY-MM-DD'), 'RE0041', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0068', 'OL008', '경기도', 2800, 3100, '대졸', 'Y', to_date('2021-06-30', 'YYYY-MM-DD'), 'RE0042', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0422', 'OL008', '광주광역시', 2800, 3700, '고졸', 'N', NULL, 'RE0043', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0060', 'OL008', '광주광역시', 2400, 3000, '대졸', 'Y', to_date('2021-06-27', 'YYYY-MM-DD'), 'RE0044', 'TASK002');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0323', 'OL008', '서울특별시', 2300, 3400, '초대졸', 'N', NULL, 'RE0045', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0121', 'OL008', '광주광역시', 2400, 3700, '대졸', 'Y', to_date('2021-05-20', 'YYYY-MM-DD'), 'RE0046', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0075', 'OL008', '강원도', 2700, 3100, '초대졸', 'Y', to_date('2021-06-17', 'YYYY-MM-DD'), 'RE0047', 'TASK002');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0036', 'OL008', '강원도', 2800, 3800, '대졸', 'N', NULL, 'RE0048', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0383', 'OL008', '제주특별자치도', 2500, 3500, '고졸', 'Y', to_date('2021-07-12', 'YYYY-MM-DD'), 'RE0049', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0363', 'OL008', '광주광역시', 2500, 3700, '대졸', 'Y', to_date('2021-05-02', 'YYYY-MM-DD'), 'RE0036', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0347', 'OL008', '제주특별자치도', 2800, 3000, '고졸', 'Y', to_date('2021-06-21', 'YYYY-MM-DD'), 'RE0037', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0235', 'OL008', '경기도', 2600, 3700, '고졸', 'N', NULL, 'RE0038', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0480', 'OL008', '부산광역시', 2200, 3200, '초대졸', 'Y', to_date('2021-07-11', 'YYYY-MM-DD'), 'RE0039', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0005', 'OL008', '서울특별시', 2600, 3300, '고졸', 'N', NULL, 'RE0040', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0253', 'OL008', '광주광역시', 2400, 3000, '고졸', 'Y', to_date('2021-05-04', 'YYYY-MM-DD'), 'RE0041', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0088', 'OL008', '부산광역시', 2700, 3200, '대졸', 'Y', to_date('2021-07-03', 'YYYY-MM-DD'), 'RE0042', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0238', 'OL008', '부산광역시', 2500, 3200, '고졸', 'Y', to_date('2021-05-18', 'YYYY-MM-DD'), 'RE0043', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0134', 'OL008', '제주특별자치도', 2000, 3700, '초대졸', 'N', NULL, 'RE0044', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0282', 'OL008', '광주광역시', 2400, 3600, '대졸', 'Y', to_date('2021-05-19', 'YYYY-MM-DD'), 'RE0045', 'TASK004');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0423', 'OL008', '부산광역시', 2600, 3100, '대졸', 'Y', to_date('2021-07-24', 'YYYY-MM-DD'), 'RE0046', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0046', 'OL008', '부산광역시', 2600, 3200, '대졸', 'Y', to_date('2021-07-28', 'YYYY-MM-DD'), 'RE0047', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0037', 'OL008', '경기도', 2300, 3200, '대졸', 'Y', to_date('2021-06-14', 'YYYY-MM-DD'), 'RE0048', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0301', 'OL008', '강원도', 2100, 3200, '초대졸', 'N', NULL, 'RE0049', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0337', 'OL008', '서울특별시', 2600, 3400, '고졸', 'Y', to_date('2021-05-27', 'YYYY-MM-DD'), 'RE0036', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0459', 'OL008', '강원도', 2300, 3500, '대졸', 'Y', to_date('2021-06-05', 'YYYY-MM-DD'), 'RE0037', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0198', 'OL008', '부산광역시', 2400, 3700, '대졸', 'Y', to_date('2021-05-22', 'YYYY-MM-DD'), 'RE0038', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0226', 'OL009', '강원도', 2000, 3800, '고졸', 'Y', to_date('2021-09-27', 'YYYY-MM-DD'), 'RE0039', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0433', 'OL009', '제주특별자치도', 2100, 3800, '대졸', 'Y', to_date('2021-09-25', 'YYYY-MM-DD'), 'RE0040', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0445', 'OL009', '광주광역시', 2400, 3300, '고졸', 'Y', to_date('2021-08-27', 'YYYY-MM-DD'), 'RE0041', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0044', 'OL009', '경기도', 2600, 3800, '대졸', 'Y', to_date('2021-08-21', 'YYYY-MM-DD'), 'RE0042', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0149', 'OL009', '강원도', 2600, 3100, '초대졸', 'Y', to_date('2021-09-01', 'YYYY-MM-DD'), 'RE0043', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0154', 'OL009', '제주특별자치도', 2000, 3500, '고졸', 'N', NULL, 'RE0044', 'TASK005');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0182', 'OL009', '광주광역시', 2800, 3000, '대졸', 'Y', to_date('2021-08-19', 'YYYY-MM-DD'), 'RE0045', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0128', 'OL009', '광주광역시', 2800, 3700, '대졸', 'Y', to_date('2021-08-18', 'YYYY-MM-DD'), 'RE0046', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0364', 'OL009', '광주광역시', 2400, 3700, '고졸', 'Y', to_date('2021-09-18', 'YYYY-MM-DD'), 'RE0047', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0393', 'OL009', '서울특별시', 2400, 3700, '고졸', 'Y', to_date('2021-09-27', 'YYYY-MM-DD'), 'RE0048', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0103', 'OL009', '부산광역시', 2000, 3200, '대졸', 'N', NULL, 'RE0049', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0357', 'OL009', '서울특별시', 2700, 3600, '고졸', 'Y', to_date('2021-10-22', 'YYYY-MM-DD'), 'RE0036', 'TASK002');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0032', 'OL009', '광주광역시', 2400, 3300, '대졸', 'Y', to_date('2021-08-19', 'YYYY-MM-DD'), 'RE0037', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0498', 'OL009', '제주특별자치도', 2000, 3200, '대졸', 'Y', to_date('2021-10-29', 'YYYY-MM-DD'), 'RE0038', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0215', 'OL009', '제주특별자치도', 2500, 3200, '고졸', 'Y', to_date('2021-09-08', 'YYYY-MM-DD'), 'RE0039', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0161', 'OL009', '제주특별자치도', 2100, 3500, '대졸', 'N', NULL, 'RE0040', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0196', 'OL009', '광주광역시', 2800, 3300, '대졸', 'Y', to_date('2021-08-20', 'YYYY-MM-DD'), 'RE0041', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0381', 'OL009', '경기도', 2000, 3500, '대졸', 'Y', to_date('2021-09-16', 'YYYY-MM-DD'), 'RE0042', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0411', 'OL009', '제주특별자치도', 2300, 3600, '고졸', 'Y', to_date('2021-10-26', 'YYYY-MM-DD'), 'RE0043', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0133', 'OL009', '강원도', 2000, 3500, '대졸', 'Y', to_date('2021-09-21', 'YYYY-MM-DD'), 'RE0044', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0286', 'OL009', '광주광역시', 2300, 3400, '초대졸', 'Y', to_date('2021-10-06', 'YYYY-MM-DD'), 'RE0045', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0358', 'OL009', '경기도', 2300, 3600, '대졸', 'Y', to_date('2021-10-20', 'YYYY-MM-DD'), 'RE0046', 'TASK004');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0315', 'OL009', '강원도', 2600, 3000, '초대졸', 'Y', to_date('2021-08-29', 'YYYY-MM-DD'), 'RE0047', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0308', 'OL009', '서울특별시', 2000, 3200, '대졸', 'Y', to_date('2021-08-22', 'YYYY-MM-DD'), 'RE0048', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0417', 'OL009', '강원도', 2000, 3000, '대졸', 'Y', to_date('2021-09-07', 'YYYY-MM-DD'), 'RE0049', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0307', 'OL009', '서울특별시', 2700, 3500, '고졸', 'N', NULL, 'RE0036', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0249', 'OL009', '강원도', 2500, 3300, '대졸', 'Y', to_date('2021-09-20', 'YYYY-MM-DD'), 'RE0037', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0138', 'OL009', '광주광역시', 2400, 3000, '대졸', 'Y', to_date('2021-08-01', 'YYYY-MM-DD'), 'RE0038', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0183', 'OL009', '경기도', 2200, 3000, '대졸', 'Y', to_date('2021-08-18', 'YYYY-MM-DD'), 'RE0039', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0416', 'OL009', '강원도', 2000, 3000, '대졸', 'Y', to_date('2021-09-10', 'YYYY-MM-DD'), 'RE0040', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0106', 'OL010', '부산광역시', 2400, 3500, '고졸', 'N', NULL, 'RE0041', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0300', 'OL010', '광주광역시', 2800, 3500, '고졸', 'Y', to_date('2021-08-05', 'YYYY-MM-DD'), 'RE0042', 'TASK005');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0468', 'OL010', '광주광역시', 2200, 3300, '고졸', 'Y', to_date('2021-10-17', 'YYYY-MM-DD'), 'RE0043', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0038', 'OL010', '경기도', 2500, 3800, '고졸', 'Y', to_date('2021-08-09', 'YYYY-MM-DD'), 'RE0044', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0013', 'OL010', '광주광역시', 2500, 3600, '대졸', 'Y', to_date('2021-09-25', 'YYYY-MM-DD'), 'RE0045', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0171', 'OL010', '서울특별시', 2100, 3600, '초대졸', 'Y', to_date('2021-08-08', 'YYYY-MM-DD'), 'RE0046', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0473', 'OL010', '광주광역시', 2300, 3100, '대졸', 'Y', to_date('2021-08-03', 'YYYY-MM-DD'), 'RE0047', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0004', 'OL010', '강원도', 2600, 3300, '대졸', 'N', NULL, 'RE0048', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0035', 'OL010', '서울특별시', 2000, 3700, '대졸', 'Y', to_date('2021-10-14', 'YYYY-MM-DD'), 'RE0049', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0276', 'OL010', '광주광역시', 2500, 3400, '초대졸', 'Y', to_date('2021-09-22', 'YYYY-MM-DD'), 'RE0036', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0294', 'OL010', '부산광역시', 2000, 3400, '대졸', 'N', NULL, 'RE0037', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0160', 'OL010', '광주광역시', 2700, 3700, '대졸', 'Y', to_date('2021-09-25', 'YYYY-MM-DD'), 'RE0038', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0152', 'OL010', '부산광역시', 2600, 3800, '고졸', 'Y', to_date('2021-10-04', 'YYYY-MM-DD'), 'RE0039', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0007', 'OL010', '제주특별자치도', 2200, 3700, '고졸', 'Y', to_date('2021-08-17', 'YYYY-MM-DD'), 'RE0040', 'TASK004');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0066', 'OL010', '광주광역시', 2100, 3400, '고졸', 'Y', to_date('2021-10-26', 'YYYY-MM-DD'), 'RE0041', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0497', 'OL010', '경기도', 2200, 3100, '고졸', 'Y', to_date('2021-10-03', 'YYYY-MM-DD'), 'RE0042', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0392', 'OL010', '제주특별자치도', 2200, 3000, '대졸', 'Y', to_date('2021-09-19', 'YYYY-MM-DD'), 'RE0043', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0022', 'OL010', '경기도', 2100, 3200, '고졸', 'Y', to_date('2021-08-08', 'YYYY-MM-DD'), 'RE0045', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0409', 'OL010', '광주광역시', 2600, 3400, '대졸', 'N', NULL, 'RE0046', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0218', 'OL010', '강원도', 2400, 3200, '대졸', 'Y', to_date('2021-10-21', 'YYYY-MM-DD'), 'RE0047', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0397', 'OL010', '제주특별자치도', 2100, 3500, '초대졸', 'Y', to_date('2021-10-02', 'YYYY-MM-DD'), 'RE0048', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0177', 'OL010', '부산광역시', 2800, 3500, '고졸', 'N', NULL, 'RE0049', 'TASK005');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0303', 'OL010', '강원도', 2700, 3200, '대졸', 'Y', to_date('2021-09-13', 'YYYY-MM-DD'), 'RE0036', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0141', 'OL010', '부산광역시', 2500, 3800, '초대졸', 'Y', to_date('2021-08-20', 'YYYY-MM-DD'), 'RE0037', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0426', 'OL010', '광주광역시', 2400, 3100, '고졸', 'Y', to_date('2021-10-07', 'YYYY-MM-DD'), 'RE0038', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0410', 'OL011', '광주광역시', 2600, 3700, '대졸', 'Y', to_date('2021-10-18', 'YYYY-MM-DD'), 'RE0039', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0479', 'OL011', '제주특별자치도', 2500, 3500, '대졸', 'Y', to_date('2021-09-28', 'YYYY-MM-DD'), 'RE0040', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0284', 'OL011', '서울특별시', 2300, 3300, '대졸', 'N', NULL, 'RE0041', 'TASK002');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0258', 'OL011', '경기도', 2500, 3200, '고졸', 'Y', to_date('2021-08-14', 'YYYY-MM-DD'), 'RE0042', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0305', 'OL011', '서울특별시', 2200, 3500, '대졸', 'Y', to_date('2021-08-28', 'YYYY-MM-DD'), 'RE0043', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0487', 'OL011', '광주광역시', 2100, 3200, '고졸', 'Y', to_date('2021-08-24', 'YYYY-MM-DD'), 'RE0044', 'TASK002');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0465', 'OL011', '서울특별시', 2200, 3700, '대졸', 'N', NULL, 'RE0045', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0071', 'OL011', '제주특별자치도', 2000, 3500, '대졸', 'Y', to_date('2021-10-06', 'YYYY-MM-DD'), 'RE0046', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0467', 'OL011', '경기도', 2000, 3200, '대졸', 'N', NULL, 'RE0047', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0084', 'OL011', '제주특별자치도', 2000, 3400, '대졸', 'Y', to_date('2021-10-04', 'YYYY-MM-DD'), 'RE0048', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0168', 'OL011', '광주광역시', 2500, 3100, '초대졸', 'Y', to_date('2021-09-21', 'YYYY-MM-DD'), 'RE0049', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0231', 'OL011', '경기도', 2500, 3800, '고졸', 'Y', to_date('2021-09-01', 'YYYY-MM-DD'), 'RE0036', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0002', 'OL011', '강원도', 2800, 3300, '대졸', 'N', NULL, 'RE0037', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0309', 'OL011', '제주특별자치도', 2500, 3800, '대졸', 'Y', to_date('2021-08-12', 'YYYY-MM-DD'), 'RE0038', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0268', 'OL011', '서울특별시', 2100, 3400, '대졸', 'Y', to_date('2021-09-05', 'YYYY-MM-DD'), 'RE0039', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0328', 'OL011', '광주광역시', 2200, 3600, '고졸', 'Y', to_date('2021-08-19', 'YYYY-MM-DD'), 'RE0040', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0014', 'OL011', '제주특별자치도', 2600, 3100, '고졸', 'Y', to_date('2021-09-16', 'YYYY-MM-DD'), 'RE0041', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0033', 'OL011', '광주광역시', 2400, 3500, '고졸', 'Y', to_date('2021-08-07', 'YYYY-MM-DD'), 'RE0042', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0275', 'OL011', '경기도', 2300, 3300, '대졸', 'N', NULL, 'RE0043', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0481', 'OL011', '강원도', 2300, 3400, '대졸', 'Y', to_date('2021-09-16', 'YYYY-MM-DD'), 'RE0044', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0086', 'OL011', '제주특별자치도', 2700, 3800, '고졸', 'N', NULL, 'RE0045', 'TASK005');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0115', 'OL011', '서울특별시', 2100, 3500, '초대졸', 'N', NULL, 'RE0047', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0373', 'OL011', '강원도', 2300, 3800, '고졸', 'Y', to_date('2021-10-11', 'YYYY-MM-DD'), 'RE0046', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0389', 'OL011', '제주특별자치도', 2600, 3000, '고졸', 'Y', to_date('2021-09-20', 'YYYY-MM-DD'), 'RE0049', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0137', 'OL011', '서울특별시', 2600, 3200, '대졸', 'Y', to_date('2021-09-24', 'YYYY-MM-DD'), 'RE0036', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0429', 'OL012', '경기도', 2800, 3100, '고졸', 'Y', to_date('2021-05-10', 'YYYY-MM-DD'), 'RE0037', 'TASK002');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0001', 'OL012', '제주특별자치도', 2100, 3800, '대졸', 'N', NULL, 'RE0038', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0451', 'OL012', '강원도', 2800, 3200, '대졸', 'Y', to_date('2021-06-10', 'YYYY-MM-DD'), 'RE0039', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0344', 'OL012', '부산광역시', 2200, 3100, '대졸', 'Y', to_date('2021-05-01', 'YYYY-MM-DD'), 'RE0040', 'TASK002');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0132', 'OL012', '서울특별시', 2500, 3400, '대졸', 'N', NULL, 'RE0041', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0082', 'OL012', '강원도', 2500, 3600, '대졸', 'Y', to_date('2021-04-16', 'YYYY-MM-DD'), 'RE0042', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0407', 'OL012', '부산광역시', 2200, 3100, '대졸', 'Y', to_date('2021-04-25', 'YYYY-MM-DD'), 'RE0043', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0352', 'OL012', '경기도', 2400, 3300, '대졸', 'N', NULL, 'RE0044', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0471', 'OL012', '강원도', 2000, 3400, '대졸', 'Y', to_date('2021-06-08', 'YYYY-MM-DD'), 'RE0045', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0018', 'OL012', '광주광역시', 2800, 3200, '대졸', 'Y', to_date('2021-05-11', 'YYYY-MM-DD'), 'RE0046', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0270', 'OL012', '서울특별시', 2700, 3300, '고졸', 'Y', to_date('2021-06-08', 'YYYY-MM-DD'), 'RE0047', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0441', 'OL012', '부산광역시', 2700, 3600, '대졸', 'Y', to_date('2021-05-20', 'YYYY-MM-DD'), 'RE0048', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0125', 'OL012', '제주특별자치도', 2700, 3200, '대졸', 'N', NULL, 'RE0049', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0158', 'OL012', '부산광역시', 2800, 3700, '대졸', 'Y', to_date('2021-05-28', 'YYYY-MM-DD'), 'RE0036', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0079', 'OL012', '제주특별자치도', 2100, 3700, '고졸', 'Y', to_date('2021-05-30', 'YYYY-MM-DD'), 'RE0037', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0126', 'OL012', '경기도', 2500, 3000, '대졸', 'Y', to_date('2021-05-13', 'YYYY-MM-DD'), 'RE0038', 'TASK004');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0304', 'OL012', '광주광역시', 2200, 3100, '대졸', 'N', NULL, 'RE0039', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0107', 'OL012', '경기도', 2100, 3200, '대졸', 'Y', to_date('2021-05-02', 'YYYY-MM-DD'), 'RE0040', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0292', 'OL012', '부산광역시', 2700, 3500, '대졸', 'Y', to_date('2021-04-28', 'YYYY-MM-DD'), 'RE0041', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0310', 'OL012', '강원도', 2200, 3700, '고졸', 'N', NULL, 'RE0042', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0472', 'OL012', '제주특별자치도', 2200, 3300, '초대졸', 'Y', to_date('2021-05-27', 'YYYY-MM-DD'), 'RE0043', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0099', 'OL012', '서울특별시', 2400, 3100, '고졸', 'N', NULL, 'RE0044', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0104', 'OL012', '경기도', 2000, 3600, '대졸', 'Y', to_date('2021-05-20', 'YYYY-MM-DD'), 'RE0045', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0419', 'OL012', '광주광역시', 2500, 3800, '대졸', 'N', NULL, 'RE0046', 'TASK001');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0431', 'OL012', '서울특별시', 2000, 3700, '대졸', 'Y', to_date('2021-05-06', 'YYYY-MM-DD'), 'RE0047', 'TASK003');

INSERT INTO TBLJOBSEEKER (STUDENT_SEQ, OPEN_COURSE_SEQ, DESIRED_PLACE, MIN_SALARY, MAX_SALARY, ACADEMIC, EMPLOYMENT_STATE, EMPLOYMENT_DATE, RECRUITER_SEQ, TASK_SEQ) 
VALUES ('S0163', 'OL012', '부산광역시', 2500, 3200, '고졸', 'Y', to_date('2021-05-29', 'YYYY-MM-DD'), 'RE0048', 'TASK001');

select * from tblJobseeker;

commit;
