SET DEFINE OFF

INSERT INTO TBLTASK (TASK_SEQ, NAME) 
VALUES ('TASK001', '웹개발');

INSERT INTO TBLTASK (TASK_SEQ, NAME) 
VALUES ('TASK002', 'DB관리');

INSERT INTO TBLTASK (TASK_SEQ, NAME) 
VALUES ('TASK003', '백엔드개발');

INSERT INTO TBLTASK (TASK_SEQ, NAME) 
VALUES ('TASK004', '퍼블리셔');

INSERT INTO TBLTASK (TASK_SEQ, NAME) 
VALUES ('TASK005', 'SW개발');

INSERT INTO TBLTASK (TASK_SEQ, NAME) 
VALUES ('TASK006', '소프트웨어엔지니어');

select * from tbltask;

commit;